### ISSUE TITLE
Plasma-Theme Issue

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#11]
I am using Papirus-dark plasma theme and after every restart, the plasma theme looks like -- http://i.imgur.com/c9DFA11.png

Everytime after boot, I have to killall plasma & kstart plasmashell to get the theme look as it should.

**Comment by horosgrisa** [comment]
Enable "Background contrast" effect in systemsettings

**Comment by Abhishek-Rawal** [comment]
@horosgrisa It's already activated : http://i.imgur.com/mBq4fc7.png
I have to kill plasma shell : http://i.imgur.com/fm1s6v0.png
Then start plasmashell to get : http://i.imgur.com/IhgEbZW.png

**Comment by horosgrisa** [comment]
@Abhishek-Rawal What video driver you use? And check "Rendering backend" and "OpenGL interface"

**Comment by Abhishek-Rawal** [comment]
@horosgrisa Video Driver : RadeonSI
Rendering Backend : OpenGL 3.1
OGL Interface : GLX

**Comment by horosgrisa** [comment]
Change OpenGL 3.1 -> 2.0, if don't work change GLX to EGL

**Comment by Abhishek-Rawal** [comment]
@horosgrisa Thing is Dark Breeze theme is working fine with OGL3.1 and GLX, and I never had problem like that before. It's just after I switched to Papirus plasma theme, I am having this problem.
Still, Imma switch to OGL2.0 and EGL, and will report here asap!

**Comment by horosgrisa** [comment]
@Abhishek-Rawal This проблем similar to mine: https://github.com/varlesh/papirus-pack-kde/issues/3
but the problem was solved when I enable "Background contrast"

**Comment by Abhishek-Rawal** [comment]
@horosgrisa OGL2.0 and EGL - same problem.
I will rm config and cache, and will set 'BG contrast' again, and see if it works out or not.
Thanks though.

**Comment by varlesh** [comment]
This theme based on Breeze Dark. I don't know why panel use light color if contrast disabled on systemsettings. Working fine with OpenGL and GLX (Kubuntu) with Intel HD4000.

**Comment by M4dGun** [comment]
Same error here.
I have to restart plasma.

**Comment by 0x221E** [comment]
@M4dGun No need to restart plasmashell. Simply go to systemsettings -> Desktop Behaviour -> Desktop Effects and disable Background contrast -> Apply. Now, re-enable BG contrast and then hit Apply.

**Comment by varlesh** [comment]
@kalasni Oh, sorry i not see you comment.
- install Plank
- Download Plank theme and install:
```
sudo mkdir /usr/share/plank/themes/Papirus
cd /usr/share/plank/themes/Papirus
sudo wget https://raw.githubusercontent.com/varlesh/papirus-pack-kde/master/gtk-themes/papirus/plank/dock.theme
```
- Start Plank and Apply theme on preferences

Also for Dark:
- Download theme:
```
sudo mkdir /usr/share/plank/themes/PapirusDark
cd /usr/share/plank/themes/PapirusDark
sudo wget https://raw.githubusercontent.com/varlesh/papirus-pack-kde/master/gtk-themes/papirus-dark/plank/dock.theme
```
