### ISSUE TITLE
Request Regarding Yakuake Skin

### ISSUE THREAD

**Issue by Abhishek-Rawal** [varlesh/papirus-pack-kde#14]
Is it possible to get black 'scroll bar' rather than white one in Papirus-dark skin ?
http://i.imgur.com/gGWuhHe.png

That white scroll bar in yakuake skin, really kills the look of this awesome theme.

**Comment by varlesh** [comment]
Not avaiable. Yakuake use system color-scheme. But you can hide scrollbar.
Go to Settings -> Edit Current Profile (or right click anywhere in the terminal and select Edit Current Profile) ->Journal  on 'Scrollback' tab set 'Hidden' option.

**Comment by Abhishek-Rawal** [comment]
Thanks a lot :)
And thanks for awesome theme too! Keep up the good work!
