### ISSUE TITLE
Need PKGBUILDs

### ISSUE THREAD

**Issue by varlesh** [varlesh/papirus-pack-kde#2]
I would appreciate if someone create packages for Arch Linux

**Comment by horosgrisa** [comment]
@varlesh https://aur4.archlinux.org/packages/?O=0&SeB=nd&K=papirus&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by varlesh** [comment]
wow, wow ))

**Comment by varlesh** [comment]
Very good @horosgrisa!
We need packages for yakuake, bomi and libreoffice

**Comment by varlesh** [comment]
@horosgrisa
В papirus-gtk-theme для корректной работы нужно добавить движок еще в зависимости:
```depends=('gtk-engine-murrine')```
Буду признателен если еще напишите для  yakuake, bomi и libreoffice.
Для этих пакетов можно указать опциональные зависимости. Подобное уже обсуждали тут, можете глянуть https://github.com/varlesh/papirus-plasma-theme/issues/2
Делов на 5 минут :)

**Comment by horosgrisa** [comment]
Я сделал все пакеты.

**Comment by horosgrisa** [comment]
А какую вы используете тему kwin?

**Comment by varlesh** [comment]
@horosgrisa Спасибо большое )) Сейчас добавлю в ридми
Использую Breeze, с уменьшенными кнопками и отключенной опцией "Рисовать круг вокруг кнопки закрытия"

**Comment by varlesh** [comment]
@horosgrisa 
Опция --aur-url https://aur4.archlinux.org нужна или уже  yaourt переведен на новый репозиторий?

**Comment by horosgrisa** [comment]
Уже не нужна

**Comment by varlesh** [comment]
ага, удалю тогда

**Comment by horosgrisa** [comment]
Так может все таки создать look-and-feel пакет?

**Comment by varlesh** [comment]
Ну ты же уже указал рекомендуемые пакеты вроде.

**Comment by horosgrisa** [comment]
Нет, look-and-feel пакет это и тема плазмы, и иконок, и ksplash, и многое другое:

```sh
ls /usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/

components/  desktopswitcher/  lockscreen/  loginmanager/  logout/  osd/  previews/  runcommand/  splash/  userswitcher/  windowdecoration/  windowswitcher/  defaults

```

**Comment by varlesh** [comment]
А, понял. Но у нас нету сплешей никаких

**Comment by varlesh** [comment]
Это про типа "Внешний вид рабочей среды" да?

**Comment by horosgrisa** [comment]
И активируя его все остальные настройки подхватываются автоматически
![](https://cloud.githubusercontent.com/assets/4980269/9289620/f6fcca06-437f-11e5-888f-11ab976249f8.png)

**Comment by horosgrisa** [comment]
Да, именно, Внешний вид рабочей среды

**Comment by horosgrisa** [comment]
А ksplash создается очень просто: копируем из breeze и меняем фон.

**Comment by varlesh** [comment]
а мануалы есть как его делать-то?

**Comment by varlesh** [comment]
я про look-and-feel

**Comment by horosgrisa** [comment]
Да, они находятся вот здесь: `/usr/share/plasma/look-and-feel/org.kde.breeze.desktop/contents/`

**Comment by horosgrisa** [comment]
Шутка, но все очень понятно

**Comment by horosgrisa** [comment]
И не обязательно делать все, достаточно сделать насторйки для того что мы и так имеем

**Comment by horosgrisa** [comment]
Я могу попробовать сделать такой пакет

**Comment by varlesh** [comment]
оно там все на QML. Я фиг знает смогу ли

**Comment by varlesh** [comment]
@horosgrisa Кстати для панелей лучше 16х16 использовать. Так как Paper исходник такой, по-умолчанию идет 22 - они размытые
![61](https://cloud.githubusercontent.com/assets/8083855/9289672/0f94d5da-4381-11e5-83f6-7c3c99c2ca6f.png)

**Comment by horosgrisa** [comment]
А вы сами делаете иконки или только берете из Paper?

**Comment by varlesh** [comment]
В этом лук анд фил можно указать размеры значков по-умолчанию?

**Comment by horosgrisa** [comment]
Я уже начал делать.

**Comment by varlesh** [comment]
Ну как сказать. Изначально токо был Paper, потом он разросся )) В последнее время сам рисую многие

**Comment by horosgrisa** [comment]
А иконку ownCloud можете добавить?

**Comment by varlesh** [comment]
Сделаем. В иссуе напишите какие нужно.

**Comment by varlesh** [comment]
желательно формата:
app= ownCloud
icon=owncloud
и т.п.

**Comment by varlesh** [comment]
Если честно, то тут от Paper ничего не осталось. Я все значки с нуля переделывал, потому что тображение в KDE страдает. К примеру, тени и размытия могут вообще не отображаться. Поэтому пришлось их форкнуть и переделать (упростить чудок)

**Comment by varlesh** [comment]
@horosgrisa Гриш, посидел я с этим лук-энд-фил и пришел к выводу, что оно еще сырое.
Долго не мог понять откуда берутся и куда записываются параметры, но потом дошло, что это же конфиги с домашней директории.
Сделал пробный, прописал там размер значков, уменьшенные кнопки заголовок окон, отключение KSplash и т.д:
```
Theme=papirus

[kdeglobals][MainToolbarIcons]
Size=16

[kdeglobals][SmallIcons]
Size=16

[kdeglobals][Toolbar style]
ToolButtonStyle=NoText
ToolButtonStyleOtherToolbars=NoText

[kdeglobals][ToolbarIcons]
Size=22

[plasmarc][Theme]
name=papirus

[kcminputrc][Mouse]
cursorTheme=breeze_cursors

[breezerc][Common]
OutlineCloseButton=false
ShadowStrength=89

[breezerc][Windeco]
ButtonSize=ButtonSmall

[ksplashrc][KSplash]
Engine=none
Theme=None
```
Собственно, половина не работает и не применяется. Я не знаю, возможно причина в древней Plasma на Kubuntu, но вот не работает оно как надо. Значки тоже наполовину применяются, в KDE4-приложениях используются старые...

**Comment by varlesh** [comment]
В Arch такая же ситуация?

**Comment by horosgrisa** [comment]
Насколько я понимаю, там не все настройки можно указывать. Я тоже пытался изменить размер иконок, но у меня не получилось.

**Comment by horosgrisa** [comment]
А какие именно настройки применились?

**Comment by horosgrisa** [comment]
Решил я поискать документацию к look-and-feel, первая ссылка вот это: https://forum.kde.org/viewtopic.php?f=285&t=127704 ;)

**Comment by horosgrisa** [comment]
Так, я покопался в исходниках plasma-desktop. Look-and-feel изменяет только следующие настройки: 
```
ColorScheme
widgetStyle
Icons
cursorTheme
WindowSwitcher:LayoutName
```

**Comment by varlesh** [comment]
Мда, не густо. Ну вот они и применялись, только правда криво как-то все равно. Значки для KDE4-приложений все равно оставались прежние. А зарепортил баг, может вдруг добавят поддержку остального или починят https://bugs.kde.org/show_bug.cgi?id=351368

**Comment by horosgrisa** [comment]
Если я не ошибаюсь, настройки для KDE4 находятся в папке ~/.kde/share/config, а look-and-feel меняет файлы из ~/.config

**Comment by horosgrisa** [comment]
Да, look-and-feel меняет темы только для KDE5 приложений.

**Comment by varlesh** [comment]
Ну да, а там про KDE4 вообще ничего нету. Предлагаю пока заморозить этот лук-энд-фил. Может потом еще че-нить сварганим )

**Comment by horosgrisa** [comment]
В Arch почти все приложения из KDE5, скоро и в Kubuntu прийдут обновления. Что вы имеете в виду под заморозкой? Я предлагаю оставить так как есть, look-and-feel который мы имеем хуже не делает.

**Comment by varlesh** [comment]
Ну оставить как и есть, я и имел ввиду, не мурыжиться с ним пока. Если добавят новые опции в будущем, то поправим файл настройки

**Comment by horosgrisa** [comment]
Ага

**Comment by varlesh** [comment]
тогда закрываем

**Comment by horosgrisa** [comment]
Вы заметили что я решил проблему с отображением темной панели? Оказалось что я отключил эффект "Контрастность фона", и из за этого были проблемы.

**Comment by varlesh** [comment]
Это в эффектах?

**Comment by horosgrisa** [comment]
Да

**Comment by varlesh** [comment]
а лук-энд-фил цепляет эту настройку?

**Comment by horosgrisa** [comment]
Нет

**Comment by horosgrisa** [comment]
Это здесь ни при чем. Вы можете не беспокоится, этот эффект по умолчанию включен.

**Comment by varlesh** [comment]
Жаль :(
Надо это как-то указать

**Comment by varlesh** [comment]
В Kubuntu этот эффект на половину только включен

**Comment by horosgrisa** [comment]
Этого достаточно

**Comment by varlesh** [comment]
Походу нет, у меня обводка
![plasma-dark3](https://cloud.githubusercontent.com/assets/8083855/9302819/3c5861ba-44e2-11e5-9768-de283e19bc24.png)

**Comment by varlesh** [comment]
а, понял. Вы про белую панель. А я про обводку шрифтов )

**Comment by horosgrisa** [comment]
Но с обводкой нужно тоже что-то делать. Вы спрашивали на форуме kde можно ли это отключить?

**Comment by varlesh** [comment]
Вот плохо конечно, что так получилось с шрифтами в виджете. Если бы я знал, то изначально бы делал по другому... А теперь приходится либо неиспользовать этот виджет, либо править colors... А перерисовывать 500 значков что-то прям не хочется...

**Comment by varlesh** [comment]
Можно конечно попробовать скриптом заменить, но не уверен что он полностью сработает.
Спрашивать не имеет смысла, оно у них в коде где-то прописано. Начиная с 192,192,192 и ниже по диапазону применяется эффект обводки или тени

**Comment by varlesh** [comment]
Там еще нужно подобрать цвет. Потому как у всех значков прозрачность в 50%.

**Comment by horosgrisa** [comment]
Я сейчас копаюсь в коде, подождите немного

**Comment by varlesh** [comment]
Стоп, я туплю. По сути все значки это #ffffff c прозрачностью 50%. Значит надо всего лишь убавить прозрачность

**Comment by varlesh** [comment]
подобрать цвет соответствующий шрифту 193,193,193 и всё

**Comment by horosgrisa** [comment]
Я похоже нашел кусок кода, который ответственный за тень: `plasma-desktop-5.3.95/applets/taskmanager/plugin/textlabel.cpp:232`

**Comment by horosgrisa** [comment]
И он вшит намертво

**Comment by varlesh** [comment]
переписывать код это не вариант. Проще заморочиться со скриптом и подправить прозрачность. Я вот открыл значок в текст. редакторе и не могу найти чет прозрачность

**Comment by varlesh** [comment]
что-то нашел, наверн эт оно:
opacity:0.5

**Comment by varlesh** [comment]
Да, эт и есть прозрачность. Фух терь вот надо 500 значков переделать

**Comment by horosgrisa** [comment]
Use sed, @varlesh

**Comment by horosgrisa** [comment]
Используйте sed

**Comment by varlesh** [comment]
не, я через perl

**Comment by varlesh** [comment]
Так, я откланяюсь... Ща будем пробовать. Надеюсь всё получится

**Comment by varlesh** [comment]
@horosgrisa Вроде как все. sed помог :) Правда почему-то с .svgz не захотел работать, пришлось через замену/вставку в Kate сделать. Также заменил значки и шрифт в скине yakuake + по мелочи в пнгшках. Вобщем тяжеловато было, думал быстрей получится.

**Comment by horosgrisa** [comment]
Так svgz это заархивированный gzip-ом svg, он и не должен работать.

**Comment by varlesh** [comment]
Хм, странно что Kate смог открыть. Думал так и должно быть, а оказалось нет. В nano открыл, а там кракозябры. Все больше и больше влюбляюсь в кеды ))

**Comment by horosgrisa** [comment]
Я только что проверил, да Kate открывает нормально подобные файлы. Это очень круто.

**Comment by horosgrisa** [comment]
А чем вам folder-grey не понравилась?

**Comment by varlesh** [comment]
Она используется в kmail, как общая папка

**Comment by varlesh** [comment]
При использовании темной темы, папка получается черной. Как вариант можно сделать симлинк на folder в 16, а в 48 оставить какая была

**Comment by horosgrisa** [comment]
Я немного не понял, у меня папка отображается нормально:
![](https://cloud.githubusercontent.com/assets/4980269/9314958/e3402830-4534-11e5-925b-cbdf792d403a.png)

**Comment by varlesh** [comment]
У вас наверн kmail на kf5. у меня в старом вместо значка (где адрес) идет папка folder-grey. я добавил a2f023d8a3a5eefc2abd31c87bb8b06f196a9f82 там получается в темном варианте она не серая а белая с прозрачностью 72%

**Comment by varlesh** [comment]
в светлом варианте и размером 48х48, как положено - серая

**Comment by varlesh** [comment]
Вот что получается, если использовать в темном наборе папку folder-grey
![papirus-pack1](https://cloud.githubusercontent.com/assets/8083855/9315112/e6f4d150-4535-11e5-8d40-6027804875ed.png)

**Comment by horosgrisa** [comment]
Тут еще всплыв что отсутствуют иконки для 
- [ ] video-mp4
- [ ] video-x-msvideo
- [ ] audio-x-flac
- [ ] text-css
- [ ] text-html

**Comment by varlesh** [comment]
8bba0fce5d210df4fc06ff0bb1a3335af11693ab
