### ISSUE TITLE
Request For Different Konsole Icon

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#22]
The Konsole icon under Papirus Dark, doesn't look good.

![Image](http://i.imgur.com/GMprmQQ.png)

Is it possible to get alternate Konsole terminal icon ? :)

Great work! I heart papirus!

**Comment by varlesh** [comment]
Fixed c9d0da58e0b56204ecdbf20118fd2a6ab85fc01a
