### ISSUE TITLE
[Request] Couple more Icons

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#23]
1) Vim-QT
[Desktop Entry]
Type=Application
Name=vim-Qt
GenericName=An experimental Qt GUI for Vim
Comment=Qt UI written in Qt similar to its GTK counterpart gvim
Icon=vim-qt
Categories=Utility;
TryExec=qvim
Exec=qvim
Terminal=false
StartupNotify=false

2) Vivaldi-snapshot
[Desktop Entry]
Version=1.0
Name=Vivaldi (snapshot)
GenericName=Web Browser
Exec=/usr/bin/vivaldi-snapshot %U
Terminal=false
Icon=vivaldi-snapshot
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;

**Comment by varlesh** [comment]
Added symlinks 4aad2927fe58eea01bc93f3f867acaf55e704c3f

**Comment by 0x221E** [comment]
Kindly symlink Qtcreator too. Everyother QT development app except Qtcreator isn't showing correctly:
[Image](http://i.imgur.com/C2MJdJn.png)

QTcreator 
[Desktop Entry]
Type=Application
Exec=qtcreator %F
Name=Qt Creator
GenericName=C++ IDE for developing Qt applications
X-KDE-StartupNotify=true
Icon=QtProject-qtcreator
Terminal=false
Categories=Development;IDE;Qt;
MimeType=text/x-c++src;text/x-c++hdr;text/x-xsrc;application/x-designer;application/vnd.nokia.qt.qmakeprofile;application/vnd.nokia.xml.qt.resource;

**Comment by varlesh** [comment]
Add qtproject symlink,icon cuttlefish fae5051ba15a3cf04da06d848ab3ce75d0a165e4

**Comment by varlesh** [comment]
@0x221E Also added clion icons 2e743bcd1011ed8ca06d6d9f7692c4c3780d8e3c

**Comment by 0x221E** [comment]
w00t! Awesome work, man! :+1: :smiley:

**Comment by 0x221E** [comment]
**Android-File-Transfer**
[Desktop Entry]
Name=Android File Transfer (MTP)
Comment=Transfer files from/to MTP devices
Exec=android-file-transfer
Icon=android-file-transfer
StartupNotify=false
Terminal=false
Type=Application
Categories=Utility;FileTools;Filesystem;Qt;

**Comment by varlesh** [comment]
added 1b287c8eac372d23d85aa6554158d5379867cf0a
