### ISSUE TITLE
[Request] Couple Of Action Icons

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#24]
Is it possible to have few action icons like "Open Link In New tab" and "Open Link In New window" for firefox ?

[Image](http://i.imgur.com/Iq2Zb9A.png)

**Comment by varlesh** [comment]
I don't know this icons, sorry :(

**Comment by 0x221E** [comment]
It's alright, mate. You're already doing awesome work in maintaining papirus.
Keep it up! :+1: 

Closing the issue.
