### ISSUE TITLE
[Request] Missing Icon : PhotoQT & Otter Browser

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#25]
**PhotoQT**

[Desktop Entry]
Name=PhotoQt
GenericName=Image Viewer
Comment=View and manage images
Exec=photoqt %f
Icon=photoqt
Type=Application
Terminal=false
Categories=Graphics;Viewer;
MimeType=image/bmp;image/x-bmp;image/x-ms-bmp;image/dds;image/x-dds;image/gif;image/tiff;image/jp2;image/jpx;image/jpeg;image/x-mng;image/vnd.microsoft.icon;image/x-icon;image/picon;image/png;image/x-portable-anymap;image/x-portable-graymap;image/x-xbitmap;image/x-portable-bitmap;image/pbm;image/x-xpixmap;image/x-portable-pixmap;image/svg+xml;image/svg-xml;image/svg;text/xml-svg;image/vnd.wap.wbmp;image/wbm;video/x-mng;image/fits;image/g3fax;image/mat;image/matlab;image/miff;image/x-mono-bitmap;image/x-otb;image/vnd.nokia.ota-bitmap;image/x-palm;image/pcd;image/x-photo-cd;image/pcx;image/vnd.swiftview-pcx;image/x-pc-paintbrush;image/x-pc-paintbrush;image/x-pcx;image/x-pict;image/x-pix;image/sfw;image/x-sgi;image/sgi;image/tga;image/x-tga;image/targa;image/x-targa;image/tim;image/vicar;image/x-viff;image/x-wpg;image/wpg;image/x-xwindowdump;image/xwd;image/x-xwd;application/x-stardent-avs;application/x-dr-halo-bitmap;application/x-mtv;application/vnd.palm;

**Otter Browser**
[Desktop Entry]
Name=Otter Browser
GenericName=Web Browser
Icon=otter-browser
Type=Application
Categories=Network;WebBrowser;
Exec=otter-browser %u
Terminal=false
StartupNotify=false
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;

**Comment by varlesh** [comment]
4361d3d57c7725775f491934fc43564ede6ea983

**Comment by 0x221E** [comment]
Thanks :+1:
