### ISSUE TITLE
Missing Icon : Calibre & It's Components.

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#26]
*calibre-ebook-edit.desktop*
[Desktop Entry]
Version=1.0
Type=Application
Name=Edit E-book
GenericName=Edit E-books
Comment=Edit e-books in various formats
TryExec=ebook-edit
Exec=ebook-edit --detach %f
Icon=calibre-ebook-edit
Categories=Office;
MimeType=application/x-mobi8-ebook;application/epub+zip;application/vnd.openxmlformats-officedocument.wordprocessingml.document;text/html;application/xhtml+xml;

*calibre-ebook-viewer.desktop*
[Desktop Entry]
Version=1.0
Type=Application
Name=E-book Viewer
GenericName=Viewer for E-books
Comment=Viewer for E-books in all the major formats
TryExec=ebook-viewer
Exec=ebook-viewer --detach %f
Icon=calibre-viewer
Categories=Graphics;Viewer;
MimeType=application/x-cbr;application/x-cbc;application/ereader;application/oebps-package+xml;image/vnd.djvu;application/x-sony-bbeb;application/vnd.ms-word.document.macroenabled.12;application/x-mobipocket-subscription;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/x-mobipocket-ebook;application/vnd.ctc-posml;application/x-mobi8-ebook;application/epub+zip;application/x-cbz;

*calibre-gui.desktop*
[Desktop Entry]
Version=1.0
Type=Application
Name=Calibre
GenericName=E-book library management
Comment=E-book library management: Convert, view, share, catalogue all your e-books
TryExec=calibre
Exec=calibre --detach %F
Icon=calibre-gui
Categories=Office;
MimeType=application/x-cbr;application/x-cbc;application/ereader;application/oebps-package+xml;image/vnd.djvu;application/x-sony-bbeb;application/vnd.ms-word.document.macroenabled.12;application/x-mobipocket-subscription;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/x-mobipocket-ebook;application/vnd.ctc-posml;application/x-mobi8-ebook;application/epub+zip;application/x-cbz;

*calibre-lrfviewer.desktop*
[Desktop Entry]
Version=1.0
Type=Application
Name=LRF Viewer
GenericName=Viewer for LRF files
Comment=Viewer for LRF files (SONY ebook format files)
TryExec=lrfviewer
Exec=lrfviewer %f
Icon=calibre-viewer
MimeType=application/x-sony-bbeb;
Categories=Graphics;Viewer;

**Comment by varlesh** [comment]
Added a005954984628dc4676fdecc5e0ceb5437518a33
