### ISSUE TITLE
Icon Request : Alexandra & Its Derivative.

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#27]
**alexandra.desktop**

[Desktop Entry]
Type=Application
Name=Alexandra
GenericName=Video Library
Exec=alexandra
Icon=alexandra
Categories=AudioVideo;Video;Database;Qt;
Comment=Organize your video library

**alexandra_addfilms.desktop**

[Desktop Entry]
Type=Application
MimeType=video/avi;video/mp4;video/flv;video/mpeg;video/quicktime;video/vnd.rn-realvideo;video/x-matroska;video/x-ms-asf;video/x-msvideo;video/x-ms-wmv;video/x-ogm;video/x-theora;video/webm;
Exec=alexandra %U
Icon=alexandra
Categories=AudioVideo;Video;Qt;
NoDisplay=true
Name=Add to the video library
Comment=Add file(s) to your video library

**Comment by varlesh** [comment]
99692f7e2a1e6748782a7637b575e3d866764a4c
