### ISSUE TITLE
Steam Panel Icon For Papirus-Dark

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#29]
Steam Panel icon under Papirus dark doesn't look fine.

![2](https://cloud.githubusercontent.com/assets/10757422/10263041/d5c52614-69fc-11e5-958c-3de16c267b2f.png)

Thanks again for such great icon set and theme!

**Comment by varlesh** [comment]
It's strange, because used white icons:
https://github.com/varlesh/papirus-pack-kde/blob/master/icons/papirus-dark/16x16/apps/steam_tray_mono.svg
https://github.com/varlesh/papirus-pack-kde/blob/master/icons/papirus-black-panel/16x16/apps/steam_tray_mono.svg

**Comment by varlesh** [comment]
Maybe you must clear cache?
```
rm -r ~/.cache/plasma*
sudo rm -rf /var/tmp/kde*
```
And apply theme again

**Comment by 0x221E** [comment]
Did as you said. Still dark steam icon as tray.

**Comment by varlesh** [comment]
If you use papirus-black-panel icon dark?

**Comment by varlesh** [comment]
steam_tray_mono available only on 16x16/apps. Dark icon on "Papirus" icon theme. I have no idea why this is happening : (
![2015-10-03 19 37 33](https://cloud.githubusercontent.com/assets/8083855/10263903/90fffc0c-6a06-11e5-974d-6de5c01df291.png)

**Comment by ahjolinna** [comment]
the steam icon works for me, I don't know if it has anything to do with this but I'm using breeze as my icons or that I'm using public beta (steam).
grep -r steam_tray_mono:                      
Binary file .cache/icon-cache.kcache matches
Binary file .local/share/Steam/ubuntu12_32/steamui.so matches
.local/share/Steam/package/steam_client_publicbeta_ubuntu12.installed:public/steam_tray_mono.png,5405;1415731722;3187707190
