### ISSUE TITLE
Проблема с темой для плазмы

### ISSUE THREAD

**Issue by horosgrisa** [varlesh/papirus-pack-kde#3]
Темная тема выглядит вот так:
![My](https://cloud.githubusercontent.com/assets/4980269/9288976/ad6fbcf6-4369-11e5-8b4b-316490ffb52c.png)

Адолжна выглядеть вот так:
![](http://kde-look.org/CONTENT/content-pre1/170434-1.png)

Панель не отображается корректно

**Comment by varlesh** [comment]
Странно

**Comment by varlesh** [comment]
Может что с правами?

**Comment by horosgrisa** [comment]
Я уверен что нет

**Comment by varlesh** [comment]
Даже не знаю как быть... С самого начала так или после очередного обновления плазмы?
Breeze темный вариант работает корректно?

**Comment by varlesh** [comment]
Почистил у себя кеш, прикреплял панель к разным краям экрана. Как только не издевался, все равно показывает темный вариант
![60](https://cloud.githubusercontent.com/assets/8083855/9289081/4f9332cc-436c-11e5-9277-ff1b3fa1b8b8.png)

**Comment by horosgrisa** [comment]
Странно, ну да ладно... Пакет для Arch я сделал, правда сам использовать не могу.
