### ISSUE TITLE
[icon request] Copy com directory 

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#31]
Site: copy.com
[google copycom logo](https://www.google.pl/search?q=copycom+icon&es_sm=122&tbm=isch&tbo=u&source=univ&sa=X&ved=0CB8QsARqFQoTCP_c4uHJqMgCFcY7GgodJY8MYg&biw=1366&bih=680)

**Comment by varlesh** [comment]
please check

**Comment by FadeMind** [comment]
@varlesh GJ
