### ISSUE TITLE
bomi theme

### ISSUE THREAD

**Issue by ahjolinna** [varlesh/papirus-pack-kde#32]
the 'sub track' icon is missing, also both audio&sub track icon's tooltip txt gives only 'track' txt...don't if that is a bomi bug or themes

**Comment by varlesh** [comment]
I use 0.9.11 (building 2015-05-20) and skin working fine, all icons showing.
subtitle/track used icon media-view-subtitles
audio/volume/mut used icon kdenlive-show-audio

**Comment by ahjolinna** [comment]
@varlesh : well for me I can't see the sub icon (I do see the audio one). I tired both 0.9.11 and git version....also I'm using manjaro

**Comment by varlesh** [comment]
Maybe chmod 777 for icon theme?

**Comment by varlesh** [comment]
You use Papirus icon theme or other icon theme?

**Comment by varlesh** [comment]
You can specify their names icons for other icon theme on bomi.qml. Skin based on Native.

**Comment by ahjolinna** [comment]
chmod 777 did not help. and I don't use Papirus icon theme I use breeze

**Comment by varlesh** [comment]
Ok )) Change icons name on bomi.qml
For example:
```
MediaButton { icon: "audio-on"; action: "audio/track" }
MediaButton { icon: "format-text-bold"; action: "subtitle/track" }
```

**Comment by varlesh** [comment]
bomi papirus skin used native icons. If you use Breeze icon theme and skin apply breeze icons. Ehy you not use Breeze Skin for bomi?
I create new version and fix icon size. Please see this pull:
https://github.com/xylosper/bomi/pull/415

**Comment by varlesh** [comment]
It's not bug bomi theme. Breeze icon theme not have icon media-view-subtitles

**Comment by ahjolinna** [comment]
okay now I see the bold B when I tried that example...it seem breeze doesnt have any good icon that I could use, why not add those papirus icons to the theme, it seems other themes/skins have done it.

well I use breeze skin but I just test this skin and notice a problem.

also it seems u dont know about this: https://twitter.com/bomi_player/status/618745103587282945
anyway I and one of my friends (also a fedora dev) is trying to find tmp maintainer/developer for bomi

**Comment by varlesh** [comment]
This skin based on "Native" skin and mostly universal. Change icon names and problem solved. 
I create many skin for bomi (Breeze, Numix, Faenza Zukitwo, Freya etc..). But i'm not programmer, xylosper fix my skins.

**Comment by varlesh** [comment]
Bomi very good player, xylosper fine developer and man. It is unfortunate that it happened :cry: :

**Comment by ahjolinna** [comment]
so it was u who made those, I was the one who found the designer (also my friend) that made the new logo and metro & ardis ..maybe some other one...can't remember.

yeah it really sad what happened to him, I hope will come back soon...until that time arrives some kind temp dev/maintainer is needed

**Comment by varlesh** [comment]
I hope too...
bomi best player for me

**Comment by ahjolinna** [comment]
yeah it's geat player, it will be by default for chakraOS's first plasma5 ISO...mostly thanks to me  :D 
I have been helping xylosper almost from the beginning...the really early CMPlayer times...damn it has been years when I think about it :D
