### ISSUE TITLE
Missing icon for "mount device"

### ISSUE THREAD

**Issue by marhkb** [varlesh/papirus-pack-kde#37]
As you can see this icon is missing. The umount icon is there.

![missing_mount](https://cloud.githubusercontent.com/assets/3630213/10769537/e7fd8df6-7ce6-11e5-9c9d-d2a189a02c4d.png)

**Comment by varlesh** [comment]
No, mount icon as transparent - this best looking on Dolphin and small size.
16x16/emblems/emblem-mounted.svg

**Comment by varlesh** [comment]
it was intended, but unmounted icon have red dot.

**Comment by marhkb** [comment]
No, I do not mean the transparent icon and the red dot icon in dolphin. What I talk about is the missing symbol exactly where the arrow is pointing to.

When I change to breeze icon set I get a green mount symbol there.

![mount](https://cloud.githubusercontent.com/assets/3630213/10770421/7e353a72-7ceb-11e5-83da-b97fa8af827d.png)

**Comment by varlesh** [comment]
Icon not missing - icon transparent. 
no icon (transparent) - device mounted.
red dot - device not mounted.
https://github.com/NitruxSA/breeze-icon-theme/blob/master/Breeze/emblems/8/emblem-mounted.svg
https://github.com/varlesh/papirus-pack-kde/blob/master/icons/papirus/16x16/emblems/emblem-mounted.svg

**Comment by varlesh** [comment]
This icon theme use monochrome and red icons. If use monochrome icon for emblem mounted then disk icon and grey dot not good looking.

**Comment by marhkb** [comment]
Now I think I finally understand. This is a bit confusing. Plasma uses the same "mount icon" (in breeze's case the green one) but has an extra "umount icon"?
That is the reason you make the mount icon transparent?
Am I right?
![Uploading breeze.png…]()

**Comment by varlesh** [comment]
Please see sreenshot from dolphin mount and unmont disks

**Comment by varlesh** [comment]
This  icons also used on Dolphin sidebar and green icon not like me, but grey icon merges colors with drives icons.

**Comment by marhkb** [comment]
Yes that is what I stated/asked in my last post. Maybe I should file a bug against Plasma to not use the same icons. You can close this. 

Thanks for your time and effort. :)

**Comment by varlesh** [comment]
Yes, on sidebar Dolphin this icon not need - that spoils style.
No problem ))
