### ISSUE TITLE
Skype not honor GTK 2.0 papirus theme

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#38]
Skype not honor GTK 2.0 papirus theme on buttons
![1](http://i.imgur.com/J3zn19m.png)

**Comment by varlesh** [comment]
Soryy, but I'm don't know gtk, this GTK theme - mod Radiance (Ubuntu). And Skype Qt application, why you use GTK Theme? How working Orion GTK and Qt themes?

**Comment by FadeMind** [comment]
Skype don't using directly Qt4 GUI. It using GTK 2.0 theming OR clearlooks (after select).
For example gnome breeze git theme looking fine:
![1](http://i.imgur.com/9N1g2q5.png)

**Comment by FadeMind** [comment]
Papirus: 
![1](http://i.imgur.com/aOaphgo.png)

**Comment by varlesh** [comment]
I'm not use KDE now, and don't know GTK specification... Maybe in the future need to make a theme based on the Breeze Gnome.

**Comment by varlesh** [comment]
Change blue color to grey on Breeze Gnome and will be fine from Papirus ))

**Comment by marhkb** [comment]
Hi FadeMind, I know you from Arch Linux Forums.
I might be wrong, but I think skype needs some sort of lib32-breeze, which does not exist in the repos and AUR.

**Comment by FadeMind** [comment]
@marhkb NOPE. Skype using GTK 2.0 theme from /usr/share/themes/. 
Some themes have bad looking on skype (just missing some variables in theme code).
breeze-gnome-git AUR package is FULL compatible with both GNOME/GTK apps (32/64 bit) and don't need rebuild against architecture. Themes are not binaries. Themes are just config codes, CSS style sheets and PNG/SVG images sources.

Like I said: Skype Qt4 app using GTK 2 theming.

Nice to meet You.
Regards

@varlesh I force using clear looks for skype. Nothing important.
Issue close.

**Comment by FadeMind** [comment]
Just for knowledge

For proper working GTK theme in skype You need install:
`lib32-gtk-engine-murrine` and `lib32-gdk-pixbuf2`
Close and launch skype. Now GTK theme looks fine.

**Comment by varlesh** [comment]
Yes , I forgot skype - 32-bit app :laughing: 
Fine - problem solved.
