### ISSUE TITLE
Plasma theme - icon for folder view applet should be light or dark based on plasma theme, not desktop icon theme

### ISSUE THREAD

**Issue by AndydeCleyre** [varlesh/papirus-pack-kde#39]
![papirus_dark_folder_view_applet_on_plasma_panel](https://cloud.githubusercontent.com/assets/1787385/10916339/00706ac4-8229-11e5-8ebf-ec4aa2969caf.png)

As you can see in the image, the folder view icon (directly to the left of the volume icon) is difficult to see. I am using the Papirus Dark icon theme. If I change that to Papirus (light), that folder view icon darkens and looks great (but then it's difficult to see the dark icons on my dark window widgets).

**Comment by varlesh** [comment]
I'm not developer widget use system icon "folder". It's not bug Papirus.

**Comment by AndydeCleyre** [comment]
Ah, sorry, I thought that should be an icon provided by the plasma theme.

I don't know how this is to be properly handled/fixed, but the applet icon can be set manually.
