### ISSUE TITLE
Few More Missing Icons. [KiCad & It's Components, Kfoldersync & 2048-qt]

### ISSUE THREAD

**Issue by 0x221E** [varlesh/papirus-pack-kde#40]
**kicad.desktop**
[Desktop Entry]
Categories=Development;Electronics;
Comment=Design a printed circuit board
Comment[fr]=Concevoir un circuit imprimé
Exec=kicad %f
GenericName=EDA Suite
GenericName[fr]=Suite logicielle de conception électronique
Icon=kicad
MimeType=application/x-kicad-project;
Name=KiCad
Type=Application

**bitmap2component.desktop**
[Desktop Entry]
Categories=Development;Electronics;
Comment=Create a component from a bitmap for use with KiCad
Exec=bitmap2component
GenericName=EDA Suite
Icon=bitmap2component
MimeType=application/x-bitmap2component-project;
Name=Bitmap to Component Converter
Type=Application
Name[en_US]=Bitmap to Component Converter

**cvpcb.desktop**
[Desktop Entry]
Categories=Development;Electronics;
Comment=Assign footprints to symbols (part of KiCad)
Exec=cvpcb
GenericName=EDA Suite
Icon=cvpcb
MimeType=application/x-cvpcb-project;
Name=CvPcb
Type=Application
Name[en_US]=CvPcb

**eeschema.desktop**
[Desktop Entry]
Categories=Development;Electronics;
Comment=Design an electronic schematic
Comment[fr]=Dessiner des schémas électroniques
Exec=eeschema %f
GenericName=Electronic schematic design
GenericName[fr]=Saisie de schéma électronique
Icon=eeschema
MimeType=application/x-eeschema-schematic;
Name=Eeschema
Type=Application

**gerbview.desktop**
[Desktop Entry]
Categories=Development;Electronics;
Comment=View gerber files
Exec=gerbview
GenericName=EDA Suite
Icon=gerbview
MimeType=application/x-gerbview-project;
Name=GerbView
Type=Application
Name[en_US]=GerbView

**pcbcalculator.desktop**
[Desktop Entry]
Categories=Development;Electronics;
Comment=Calculator for various electronics related computations
Exec=pcb_calculator
GenericName=EDA Suite
Icon=pcbcalculator
MimeType=application/x-pcbcalculator-project;
Name=Pcb Calculator
Type=Application
Name[en_US]=Pcb Calculator

**pcbnew.desktop**
[Desktop Entry]
Categories=Development;Electronics;
Comment=Layout a printed circuit board
Exec=pcbnew %f
GenericName=EDA Suite
Icon=pcbnew
MimeType=application/x-pcbnew-pcb;
Name=Pcbnew
Type=Application
Name[en_US]=Pcbnew

**Kfoldersync**
[Desktop Entry]
Categories=Qt;KDE;Utility;Archiving;
DBusActivatable=true
Exec=kfoldersync
GenericName=Folder synchronization and backup tool
GenericName[de]=Werkzeug zur Verzeichnissynchronisierung und -sicherung
GenericName[es]=Herramienta de copia de seguridad y sincronización de carpetas 
GenericName[it]=Strumento di sincronizzazione e backup di cartelle
GenericName[pl]=Narzędzie do synchronizacji i tworzenia kopii zapasowej katalogu
GenericName[pt_BR]=Ferramenta de sincronização de pastas e backup
GenericName[ro]=Instrument pentru sincronizare dosare şi backup
GenericName[ru]=Утилита для создания бэкапов и синхронизации директорий
GenericName[zh_CN]=文件夹同步和备份工具
GenericName[zh_TW]=資料夾同布及備份工具
Icon=kfoldersync
Name=KFolderSync
Name[de]=KFolderSync
Name[es]=KFolderSync
Name[it]=KFolderSync
Name[pl]=KFolderSync
Name[pt_BR]=KFolderSync
Name[ro]=KFolderSync
Name[ru]=KFolderSync
Name[zh_CN]=KFolderSync
Name[zh_TW]=KFolderSync
Type=Application

**2048-qt**
[Desktop Entry]
Name=2048-Qt
GenericName=2048-Qt
Comment=The 2048 number game implemented in Qt
Comment[fr]=Jeu de réflexion et de mathématique
Exec=2048-qt
Icon=2048-qt
Terminal=false
Type=Application
Categories=Game;Math;Qt;

Thanks again for an awesome theme suite! Make my Plasma looks dope!

**Comment by varlesh** [comment]
@0x221E Chek and close

**Comment by 0x221E** [comment]
You're bloody fast! Thanks a lot.
