### ISSUE TITLE
1-pixel wide gap exposing the desktop background above the taskbar.

### ISSUE THREAD

**Issue by arcooke** [varlesh/papirus-pack-kde#41]
I'm on Mint 17.2 KDE (Plasma 4)

There's a very minor issue (but annoying enough to bring me here) that I have with Papirus.  There's a 1-pixel wide gap that exposes whatever is behind the maximized window.  The gap will appear and disappear as you adjust the height of the taskbar.  It disappears as you drag the taskbar height up, but will appear as soon as you stop resizing.

Please see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/6278400/11008304/3b445d36-8495-11e5-9e10-f77cac44afa0.png)

The dark line is my desktop background.  The part of the dark line that is white, is actually KCalc open in the background.

I don't seem to have this issue with any other themes, so I figured I'd swing by and mention it.  Any chance this could get looked at?

**Comment by varlesh** [comment]
KDE 4 have legacy support and I’m not use this DE now. I don't know why this happened, sorry.
Maybe change image panel background widget? For example, use Dynamo Plasma Theme.
Download Dynamo and extract archive:
http://hombremaledicto.deviantart.com/art/Dynamo-Plasma-beta-473014317
Go to  "widget" folder, copy "background.svgz" to Papirus "widget" folder and replace file.

**Comment by varlesh** [comment]
My theme - this original Breeze. I change blue colour on grey and change opacity...

**Comment by Glutanimate** [comment]
First of all, major thanks for creating Papirus, @varlesh. It's my favorite KDE theme suite by far.

I am also experiencing this issue on Kubuntu 14.04. This doesn't seem to exclusive to horizontal panels, either. My vertical dock has similar glitches on it's left border:

![scr2](https://cloud.githubusercontent.com/assets/5459332/11725112/397c033e-9f78-11e5-8094-571486d11c34.png)

Do you have any idea what could be the cause of this? I'd really love to stay with Papirus, but this glitch is starting to become distracting.

**Comment by varlesh** [comment]
@Glutanimate Big thx :smile: 
But, i realy don't know why this happened.
Temporary solution - use Dynamo theme or use Plank dock with Papirus skins:
https://github.com/varlesh/papirus-pack-kde/tree/master/gtk-themes/papirus/plank
https://github.com/varlesh/papirus-pack-kde/tree/master/gtk-themes/papirus-dark/plank

**Comment by varlesh** [comment]
Themes update, please reinstall.

**Comment by arcooke** [comment]
Thanks so much for updating it varlesh!  Very much appreciated.. the update fixed the issue for me.
