### ISSUE TITLE
Icons for some GTK+ applications

### ISSUE THREAD

**Issue by feskyde** [varlesh/papirus-pack-kde#42]
There are the applications name and their KDE/Qt counterpart (if had one):

- Kazam (SimpleScreenRecorder)
- GNOME MPlayer (SMPlayer)
- Polari (Konversation)
- GNOME Sound Recorder

The rest of my desktop (Arch Linux + Cinnamon) taken the theme, thanks for support GTK! :smile:

**Comment by varlesh** [comment]
Please move issue to here (For GTK DE):
https://github.com/varlesh/papirus-gtk-icon-theme
