### ISSUE TITLE
GTK Scrollbars

### ISSUE THREAD

**Issue by Israphel** [varlesh/papirus-pack-kde#43]
Should not the GTK scrollbars be themed too?
![scrolls](https://cloud.githubusercontent.com/assets/720191/11070008/00d1968e-87b8-11e5-9fe7-98d79b8594de.png)
![scrolls1](https://cloud.githubusercontent.com/assets/720191/11070009/00d3934e-87b8-11e5-830a-7e388dea77d1.png)

**Comment by varlesh** [comment]
You install packages *gtk-engine-murrine* and *gdk-pixbuf2* ?

**Comment by Israphel** [comment]
Thank you. Now they have style. They're not exactly as in plasma but they look cool.
