### ISSUE TITLE
[icon request][places] folder-copy-cloud folder-red folder-linux folder-java folder-steam

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#48]
folder-copy-cloud.svg (for http://www.copy.com storage)
folder-java.svg
folder-linux.svg
folder-steam.svg
folder-red.svg is GRAY instead of RED
folder-meocloud.svg
folder-apple.svg

[reference scheme and looking](https://github.com/franksouza183/EvolvereSuit/tree/master/icons/evolvere/places/64)

**Comment by varlesh** [comment]
folder-gray use as root directory on Dolphin and spoils style.

**Comment by FadeMind** [comment]
![s](https://i.imgur.com/ngKjFNJ.png)
