### ISSUE TITLE
[icon request] PNG custom tray icons for octopi

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#49]
Like You see Octopi Pacman GUI using customized octopi_red/yellow/green icon in tray
![s](https://i.imgur.com/IEQc5Dn.png)

![octopi_green](https://cloud.githubusercontent.com/assets/9846948/11594941/1c110b5c-9aad-11e5-8614-684e9fa2fd3d.png)
![octopi_red](https://cloud.githubusercontent.com/assets/9846948/11594942/1c14c472-9aad-11e5-82d6-26d57d87c4f5.png)
![octopi_transparent](https://cloud.githubusercontent.com/assets/9846948/11594943/1c19d516-9aad-11e5-8bd2-be57e31a3dac.png)
![octopi_yellow](https://cloud.githubusercontent.com/assets/9846948/11594945/1c71c37a-9aad-11e5-9807-9ee0dd45f01e.png)
![octopi](https://cloud.githubusercontent.com/assets/9846948/11594944/1c5bd60a-9aad-11e5-8cfe-6f0a3d80d7ba.png)

ZIP: [octopi_customs.zip](https://github.com/varlesh/papirus-pack-kde/files/52246/octopi_customs.zip)

In default Octopi using icons from: `/usr/share/icons/` dir.
These files (customized) should be added in papirus in PATH:
`/usr/share/icons/papirus/extra-icons/octopi` with README note about it, where replace them.

NOTE: octopi itself using icons from binary octopi file (adjusted before compile)
See: https://github.com/FadeMind/archpkgbuilds/tree/master/AUR/packages-git/octopi-frameworks-git

**Comment by FadeMind** [comment]
I customized octopi built in icon theme. Sources are here: 
ZIP ready for use: https://github.com/FadeMind/archpkgbuilds/raw/master/AUR/packages-git/octopi-frameworks-git/images.zip
Content: https://github.com/FadeMind/archpkgbuilds/tree/master/AUR/packages-git/octopi-frameworks-git/papirus_octopi_theme

Looking after customize octopi: 
![screenshot_20151205_084708](https://cloud.githubusercontent.com/assets/9846948/11606754/e53ee04c-9b2c-11e5-975a-4ce62cc25ddd.png)
![screenshot_20151205_084756](https://cloud.githubusercontent.com/assets/9846948/11606758/f7e7c4b6-9b2c-11e5-969a-5e894a8a9036.png)

I forgot mention about main issue. images directory content should be customized BEFORE compiling. In proccess compilling octopi app using customized icons everywhere (including icons in /usr/share/icons/ directory). 

Regards

**Comment by varlesh** [comment]
I delete icons and close - it's octopi problem, not papirus.
