### ISSUE TITLE
[icon request] [apps] zuluCrypt and zuluMount

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#50]
ZuluCrypt
https://github.com/mhogomchungu/zuluCrypt
Icons names:
zuluCrypt.svg
zuluMount.svg

Current looking:
![q](http://i.imgur.com/HzbxgAi.png)
DESKTOP:
![v](http://i.imgur.com/AHwoXqZ.png)

**Comment by FadeMind** [comment]
Like octopi, zulucrypt using built in binary file icons in tray #49:
![screenshot_20151204_221635](https://cloud.githubusercontent.com/assets/9846948/11601658/d863f3ce-9ad4-11e5-8ed9-636279703c53.png)
Infact both are Qt5 apps.

Regards

**Comment by FadeMind** [comment]
ZuluCrypt icon tray AFTER replaced them in SRC (48x48px):
![screenshot_20151205_090656](https://cloud.githubusercontent.com/assets/9846948/11606836/9d1538c2-9b2f-11e5-8eb1-181aed56d712.png)

**Comment by FadeMind** [comment]
Just add zulucrypt directory in `/usr/share/icons/papirus/extra-icons/tray/`
[zulucrypt.zip](https://github.com/varlesh/papirus-pack-kde/files/52777/zulucrypt.zip)

**Comment by varlesh** [comment]
If icon use from binary - I will not add icons on "extra-icons" folder. Because this developer solution and zulu* problem.
extra-icons - this directory from hardcoded icons, but not from binary files.
