### ISSUE TITLE
[papirus-konsole-colorscheme] value results from inxi tool are unreadable in Papirus color scheme

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#51]
Papirus theme:
![screenshot_20151204_210308](https://cloud.githubusercontent.com/assets/9846948/11600100/d22166f4-9aca-11e5-87d4-fd4eb6fb6f45.png)
Papirus Dark theme:
![screenshot_20151204_210227](https://cloud.githubusercontent.com/assets/9846948/11600095/cdd61676-9aca-11e5-8c87-fa2cb9f38b40.png)

FIX

8TH INTENSIVE COLOR should be #00B9A8
SCREENSHOT with fix:
![1](https://i.imgur.com/HA1MGcO.png)
![2](https://i.imgur.com/FonLd8D.png)

**Comment by FadeMind** [comment]
PATCH with fix:

    --- a/Papirus.colorscheme	2015-12-04 20:38:30.000000000 +0100
    +++ b/Papirus.colorscheme	2015-12-04 21:16:53.000000000 +0100
    @@ -47,7 +47,7 @@
     Color=188,188,189
     
     [Color7]
    -Color=228,228,229
    +Color=0,185,168
     
     [Color7Intense]
     Color=239,240,241

Best Regards

**Comment by varlesh** [comment]
@FadeMind Please tell QtCurve settings available on Arch?
I install qtcurve-gtk2, qtcurve-qt4, qtcurve-qt5 and qtcurve-utils - but settings button not active.
![6](https://cloud.githubusercontent.com/assets/8083855/11607517/bb998ba6-9b5a-11e5-945e-c53dfc923a94.png)

**Comment by FadeMind** [comment]
Purge all installed qtcurve packages from arch repo first.
Grab:
`git clone https://aur.archlinux.org/qtcurve-git.git`
`cd qtcurve-git/`
`makepkg -srci`
lib32 libs:
`git clone https://aur.archlinux.org/lib32-qtcurve-git.git`
`cd lib32-qtcurve-git/`
`makepkg -srci`

https://aur.archlinux.org/pkgbase/lib32-qtcurve-git/
https://aur.archlinux.org/pkgbase/qtcurve-git/
Proof:
![screenshot_20151205_124503](https://cloud.githubusercontent.com/assets/9846948/11607632/06aeda04-9b4e-11e5-9452-42caed0f6f25.png)

**Comment by varlesh** [comment]
Big Thx :smiley:
