### ISSUE TITLE
[symlink] prepare for libreoffice 5.1

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#58]
`#!/bin/bash`
`for d in 32x32 48x48`
`do`
`cd /usr/share/icons/papirus/$d/apps/`
`for r in base calc draw impress math writer`
`do`
`ln -s ./libreoffice-$r.svg ./libreoffice5.1-$r.svg`
`done`
`ln -s ./libreoffice-main.svg ./libreoffice5.1-startcenter.svg`
`done`
@varlesh

**Comment by varlesh** [comment]
Oh, again?! :confused:
