### ISSUE TITLE
Отсутствующие иконки/Missing icons

### ISSUE THREAD

**Issue by horosgrisa** [varlesh/papirus-pack-kde#6]
Вот список иконок, которые или отсутствуют , или не отображаются правильно.
Точки входа

- [x] folder-activities
- [x] folder-bookmark
- [x] folder-development
- [x] folder-html
- [x] folder-images
- [x] folder-image
- [x] folder-important
- [x] folder-locked
- [x] folder-mail
- [x] folder-music
- [x] folder-network
- [x] folder-open
- [x] folder-pictures
- [x] folder-picture
- [x] folder-print
- [x] folder-public
- [x] folder-script
- [x] folder-tar
- [x] folder-templates
- [x] folder-text
- [x] folder-txt
- [x] folder-videos

Приложения
- [x] kgpg
- [x] redshift

Устройства
- [x] media-floppy

Типы файлов
- [x] video-x-matroska (.mkv)
- [x] image-png (.png)
- [x] text-plain (.txt)
- [x] application-msword (.doc)
- [x] application-vnd.openxmlformats-officedocument.wordprocessingml.document (.docx)
- [x] application-x-php (.php)
- [x] image-jpeg (.jpg)
- [x] application-x-sqlite2
- [x] application-x-sqlite3 (.db)
- [x] application-x-rar (.rar)
- [x] image-x-svg+xml (.svg)

**Comment by varlesh** [comment]
Привет @horosgrisa  )
Вот media-floppy оно реально нужно?
Под многие папки сделаю симлинки, для mime тоже самое.

**Comment by horosgrisa** [comment]
media-floppy нужно, т.к. отображается в контекстном меню dolphin

**Comment by horosgrisa** [comment]
и в look-and-feel нужно добавить скриншот, желательно маленького размера 400/225

**Comment by varlesh** [comment]
скриншот там все равно не видно, я добавил туда значки с фоном

**Comment by varlesh** [comment]
Папки добавлены 1f719fbebabe6044e2decbd4f7dad53efe0e591b

**Comment by varlesh** [comment]
mime добавлены 7a9e42c1daeb093dc29522716671e6d3202f26b6

**Comment by varlesh** [comment]
приложения добавлены 34b782f24427afcf7f6123748d325eb32ed91fb9

**Comment by varlesh** [comment]
media-floppy добавлен ca80c30aee01cbe9aea816366234864e590bbdd5

**Comment by lonerTK** [comment]
нужна иконка)
Slimjet 
FlashPeak Slimjet
Name=FlashPeak Slimjet

**Comment by varlesh** [comment]
@lonerTK 
Имя иконки прописано в /usr/share/applications/приложение.desktop - в поле Icon=
К примеру,
Приложение = Skype
Иконка = skype
Потому как мне непонятно FlashPeak Slimjet это два или одно приложение... И имя иконки обычно в нижнем регистре пишется.

**Comment by varlesh** [comment]
Иконка уже нарисована, осталось только указать имя
![slimjet](https://cloud.githubusercontent.com/assets/8083855/9341453/9c8503a0-45fe-11e5-9b11-27f9eea6b125.png)

**Comment by varlesh** [comment]
добавил slimjet и crossover ca8a010a01800dba756ffbc33e5b7e4497f64f32

**Comment by horosgrisa** [comment]
@varlesh Как же я забыл, отсувствуют следующие mime
- [ ] application-pgp-encrypted
- [ ] application-pgp-keys
- [ ] application-pgp-signature

**Comment by varlesh** [comment]
36517331dca364463080f7d38b736a0c27ef99b2

**Comment by varlesh** [comment]
@horosgrisa вроде поправил.
Гриш, если не трудно то протестируйте pim-приложения kf5, добавил много значков - должно все отображаться в одном стиле

**Comment by horosgrisa** [comment]
Отсувствуют несколько иконок:
Иконка адрессной книги:
![after40](https://cloud.githubusercontent.com/assets/4980269/9361654/1feed9f4-46a5-11e5-9904-e74d2b474a2a.png)
Иконка "Сохранить вложение":
![after41](https://cloud.githubusercontent.com/assets/4980269/9361662/316b5e82-46a5-11e5-97af-009dbd124078.png)
Иконки "Ответить ..."
![after42](https://cloud.githubusercontent.com/assets/4980269/9361667/3dd061cc-46a5-11e5-8cbf-38bd6928a761.png)

**Comment by horosgrisa** [comment]
И опять о JavaScript: нарисуйте пожалуйста иконку с {;} , а не </> . Как здесь в breeze

**Comment by horosgrisa** [comment]
И иконки для svg

**Comment by varlesh** [comment]
@horosgrisa Давайте разберемся сначала с kf5, потом mime займемся.
Собственно, нужны симлинки для недостающих значков. Так как у меня KF5 старый, то я не знаю какие там имена. Breeze походу тоже не подцепились...Как быть?

**Comment by horosgrisa** [comment]
У меня бета kde applications 15.08, может быть из-за этого не работает. Наверно не стоит спешить, оставьте  все как есть. В панелях все нормально, я не заметил breeze нигде.

**Comment by varlesh** [comment]
Ладно. Тогда проверьте javascript a2f66ea426dd67a972af82ca50aa8f0d2dce92e0

**Comment by varlesh** [comment]
Я уже с ней запутался

**Comment by horosgrisa** [comment]
Добавьте иконку k4dirstat
```
Name=K4DirStat
Icon=k4dirstat
```

**Comment by varlesh** [comment]
d86def65f0b90bcbca9a3172d502f6ab4418bdaf

**Comment by horosgrisa** [comment]
Что случилось с инонкой выключения?
![after43](https://cloud.githubusercontent.com/assets/4980269/9366490/61da4a72-46c0-11e5-8b0a-06223d9299b7.png)

**Comment by varlesh** [comment]
ее пришлось добавить для поддержки kde4

**Comment by horosgrisa** [comment]
А все эти иконки в одном стиле можно изменить? Потому что черные иконки плохо смотрется.

**Comment by varlesh** [comment]
проверьте 7f65e9536209b486b3bfffd318c5f699450eb9c5

**Comment by varlesh** [comment]
Увидел еще HP иконку у вас на скрине, может симлинк на принтер сделаем? Подскажите имя

**Comment by horosgrisa** [comment]
```
Name=HP Device Manager
Icon=/usr/share/hplip/data/images/128x128/hp_logo.png
```
Ха-Ха...

**Comment by varlesh** [comment]
ну и фиг с ней!

**Comment by horosgrisa** [comment]
Но вот это можно добавить:
```
Name=Akonadi Console
Icon=akonadiconsole
```

**Comment by varlesh** [comment]
ммм, симлинк на аконадитрей?

**Comment by horosgrisa** [comment]
Да

**Comment by varlesh** [comment]
ок. значки в новом виджете подцепились?

**Comment by horosgrisa** [comment]
Не все
![after45](https://cloud.githubusercontent.com/assets/4980269/9367208/9ef2d736-46c4-11e5-873d-e31aaa608309.png)
Но те что вы сделали выглядят супер.

**Comment by varlesh** [comment]
добавлен аконадиконсоле 81a5a62ad7bd62abfd83de169a25a8a741e9df6c

**Comment by horosgrisa** [comment]
Отсувствует kompare
```
Name=Kompare
Icon=kompare
```

**Comment by varlesh** [comment]
погодите, сейчас с кнопками завершения пока

**Comment by horosgrisa** [comment]
Для qml лучше использовать иконку javascript синего или примерно такого цвета #607D8B

**Comment by varlesh** [comment]
проверьте системные иконки 3b6e54abe80232c2e9ae6dc6d50b1da951e455b9

**Comment by varlesh** [comment]
qml добавлен b8302a1181d78295600a193ace76a08269e88474

**Comment by horosgrisa** [comment]
Системные иконки есть

**Comment by varlesh** [comment]
@horosgrisa kompare может симлинк на kdiff3?

**Comment by varlesh** [comment]
вроде одно и тоже

**Comment by varlesh** [comment]
сделаю вариацию зелено-синего

**Comment by horosgrisa** [comment]
Да, можно симлинк

**Comment by horosgrisa** [comment]
Иконка пометить все как прочитанное выглядит слишком прямоугольной, можно ее сделать квадратной?

**Comment by horosgrisa** [comment]
![after46](https://cloud.githubusercontent.com/assets/4980269/9367706/cecae522-46c7-11e5-8759-9a804a0c749a.png)

**Comment by varlesh** [comment]
это же помеченное сообщение, типа конверт

**Comment by varlesh** [comment]
они в kmail все такого типа идут

**Comment by horosgrisa** [comment]
Ах так... Может галочку сделать чуть меньше?

**Comment by horosgrisa** [comment]
Кстати, цвета для иконок mime можно брать отсюда: https://www.materialpalette.com/ . Ведь изначально paper был адаптацией material для linux.

**Comment by horosgrisa** [comment]
Кстати, а как отображаются эти иконки в GNOME?

**Comment by varlesh** [comment]
сделано 96ca25079c52c467cc96605489dbc71bf024a015

**Comment by varlesh** [comment]
ой, я даже и не знаю. Давно пробовал в юнити на убунте, пришлось допиливать. Гном не перевариваю и не использую вообще.

**Comment by horosgrisa** [comment]
Я тоже GNOME не люблю. Но скриншоты Гнома выглядят красиво.

**Comment by varlesh** [comment]
Красивше может, не спорю, но неюзабильно совсем. Да и кеды можно при желании допилить до идеала, чем мы с вами и занимаемся ))

**Comment by horosgrisa** [comment]
Кстати вы видели концепт DWD?
https://kver.wordpress.com/2014/10/25/presenting-dwd-a-candidate-for-kde-window-decorations/
https://www.phoronix.com/scan.php?page=news_item&px=MTgyOTY

**Comment by varlesh** [comment]
Типа CSD, только для кед. Интересно... надеюсь редактирование и добавление значков в панели они не уберут. И глоб.меню теперь ненужно будет

**Comment by varlesh** [comment]
Т.е. это только концепт, в планах у них этого нету?

**Comment by horosgrisa** [comment]
К сожалению только концепт.

**Comment by horosgrisa** [comment]
А мне жутко нравится CSD в Гноме

**Comment by varlesh** [comment]
Ну кто-нибудь запилит в будущем декоратор. 5-е кеды еще толком не портированы.

**Comment by horosgrisa** [comment]
Боюсь что кеды чересчур консервативны, это одновременно и хорошо, и плохо.

**Comment by varlesh** [comment]
Ну хоть не изменяют своим принципам, за это они мне и нравятся.

**Comment by horosgrisa** [comment]
Исправьте иконку PHP. Надпись <?php  и фон #673AB7

**Comment by horosgrisa** [comment]
или <? >

**Comment by horosgrisa** [comment]
Маленькая иконка folder-script неправильная. Большие иконки folder-* это папка с логотипом, а маленькие это инвертированный логотип. В случае с folder-script, маленькая иконка тоже выглядит как папка с логотипом, лучше просто инвертируйте его.

**Comment by horosgrisa** [comment]
![after48](https://cloud.githubusercontent.com/assets/4980269/9382226/79f0ee86-4747-11e5-80ac-f133e8aafa60.png)

**Comment by horosgrisa** [comment]
Добавьте иконки 

- [ ] vcs-locally-modified
- [ ] vcs-removed
- [ ] vcs-conflicting
- [ ] vcs-locally-modified-unstaged
- [ ] vcs-normal
- [ ] vcs-added
- [ ] vcs-update-required

они отображаются плагином kdesdk-dolphin-plugins вот-так
![after49](https://cloud.githubusercontent.com/assets/4980269/9382753/288aa30c-474c-11e5-96da-a65f8bc62e3b.png)

**Comment by varlesh** [comment]
@horosgrisa Так, давайте по порядку.
По поводу папок. Там вообще  стиля нету в 16х16. Некоторые папки как логотип сделаны, другие - типа уменьшенная копия большой, третьи вообще вариация на тему.
Не пойму, чем вас не устроила folder-script. Оба значка в стиле вроде

**Comment by varlesh** [comment]
заменил все 16 в одном стиле

**Comment by varlesh** [comment]
Нужно придумать значки, подскажите какие лучше:
vcs-removed = window-close
vcs-conflicting = dialog-warning
vcs-update-required = view-refresh
vcs-added = list-add

vcs-locally-modified = 
vcs-locally-modified-unstaged = 
vcs-normal =

**Comment by horosgrisa** [comment]
vcs-added - ![vcs-added](https://cloud.githubusercontent.com/assets/4980269/9387597/04f88990-476a-11e5-9f4f-d3c41e760d48.png) - list-add подходит
vcs-conflicting - ![vcs-conflicting](https://cloud.githubusercontent.com/assets/4980269/9387598/0527a626-476a-11e5-9fa7-336fb9cc7f7b.png)
vcs-locally-modified-unstaged - ![vcs-locally-modified-unstaged](https://cloud.githubusercontent.com/assets/4980269/9387600/05471f92-476a-11e5-9773-90db53ceae84.png)
vcs-locally-modified - ![vcs-locally-modified](https://cloud.githubusercontent.com/assets/4980269/9387601/0557b23a-476a-11e5-9296-c3227fa15320.png)
vcs-normal - ![vcs-normal](https://cloud.githubusercontent.com/assets/4980269/9387602/05698d52-476a-11e5-8dfb-554cd827779b.png)
vcs-removed - ![vcs-removed](https://cloud.githubusercontent.com/assets/4980269/9387603/0576bc34-476a-11e5-8970-15bb0ffa26c8.png)
vcs-update-required - ![vcs-update-required](https://cloud.githubusercontent.com/assets/4980269/9387599/0539074a-476a-11e5-8038-744d04dbf40c.png)

Но остальные не подходят. Так-же нужны иконки и 16x16 и 48x48.

**Comment by horosgrisa** [comment]
Но лучше сделать отдельные иконки

**Comment by varlesh** [comment]
Это же эмблемы. Зачем там 48рх?
Иконки vcs-normal, vcs-removed, vcs-locally-modified-unstaged очень странные...
Надо придумать что-то другое.
ЗЫ: отойду на время... если будут идеи, то пишите сюда

**Comment by horosgrisa** [comment]
Да, я посмотрел, достаточно только 16px, эти иконки есть в Oxygen, а там только png, и из-за этого они рисовали все размеры этим иконкам.

**Comment by horosgrisa** [comment]
PHP неправильный, в не </? , можно использовать только <?, но лучше <?php

**Comment by horosgrisa** [comment]
Можно сделать иконки похожими на эти: 
vcs-removed - ![emblem-dropbox-selsync](https://cloud.githubusercontent.com/assets/4980269/9388244/f391bf5c-476c-11e5-9043-bd12d7e44fcc.png)
vcs-update-required - ![emblem-dropbox-syncing](https://cloud.githubusercontent.com/assets/4980269/9388245/f39e60b8-476c-11e5-8812-884910c2c114.png)
vcs-conflicting - ![emblem-dropbox-unsyncable](https://cloud.githubusercontent.com/assets/4980269/9388246/f3ad49ca-476c-11e5-9793-17a95c00965c.png)
vcs-normal - ![emblem-dropbox-uptodate](https://cloud.githubusercontent.com/assets/4980269/9388247/f3bfbf1a-476c-11e5-8fe1-7dcad810b3c9.png)

**Comment by horosgrisa** [comment]
Это иконки из дропбокса

**Comment by horosgrisa** [comment]
Используйте следующие цвета #607D8B, #3F51B5, #F44336, #4CAF50

**Comment by varlesh** [comment]
<?php -слишком длинное. Оставлю <?

**Comment by horosgrisa** [comment]
Ну хотя-бы так

**Comment by varlesh** [comment]
Так про значки вы мне не до конца ответили. Обязательно нужно 16 и 48?
И vcs-locally-modified-unstaged значок?

**Comment by horosgrisa** [comment]
Нет, не нужно

**Comment by horosgrisa** [comment]
vcs-locally-modified-unstaged - может восклицательный знак на зеленом фоне?

**Comment by varlesh** [comment]
сделал немного по другому 803125e81bbf9bd1c70ed0e37b0f3c74074cfee7

**Comment by horosgrisa** [comment]
Супер

**Comment by horosgrisa** [comment]
@varlesh Тут вот такая ошибка появляется если запустить приложение из терминала: 
```
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/papirus/symbolic/mimetypes"

```

**Comment by varlesh** [comment]
какое приложение?
В индексе вроде все прописано:
[symbolic/mimetypes]
Context=Mimetypes
Size=16
MinSize=16
MaxSize=512
Type=Scalable

**Comment by horosgrisa** [comment]
Если любое приложение, например Dolphin или kate, запустить из консоли, в консоль выводится следующая строка
```
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/papirus/symbolic/mimetypes"
```

**Comment by varlesh** [comment]
у меня для KDE4 ругачка идет на MS-mime только
dolphin(10639) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.sheet.binary.macroEnabled.12"

**Comment by varlesh** [comment]
ага, понял. Нужно переименовать Context=MimeTypes

**Comment by varlesh** [comment]
проверьте 0a3abcc84f09f2b832e8b715756dbef9f9768b93

**Comment by horosgrisa** [comment]
@varlesh Иконка "Создать ссылку" выглядит неоднородно по сравнению с остальными.
![after50](https://cloud.githubusercontent.com/assets/4980269/9407842/c329e598-4815-11e5-94a4-854ab380ab18.png)

**Comment by varlesh** [comment]
Это в новом дельфине?
У меня в старом так:
![4](https://cloud.githubusercontent.com/assets/8083855/9408117/4b1f5abc-4818-11e5-9221-3e2b2685dbf4.png)

**Comment by varlesh** [comment]
имя иконки нужно

**Comment by varlesh** [comment]
для URL-линков есть значок еще
![insert-link](https://cloud.githubusercontent.com/assets/8083855/9408154/a8385b40-4818-11e5-819d-7edd41b19d52.png)

**Comment by horosgrisa** [comment]
Нет, это когда перетаскиваете файл и отпускаете, появляется это меню. А создание файла у меня выглядит вот так:
![after51](https://cloud.githubusercontent.com/assets/4980269/9408284/19d16d54-481a-11e5-94e5-6a03ed8faa2d.png)

**Comment by varlesh** [comment]
хм, а у меня вообще карандаш ))
![5](https://cloud.githubusercontent.com/assets/8083855/9408318/616a3a56-481a-11e5-83f1-4d23983ef609.png)

**Comment by varlesh** [comment]
я нашел этот значок. Это вроде как emblem-symbolic-link.
Но он у меня есть как симлинк на emblem-link

**Comment by horosgrisa** [comment]
А как проверить какой значек используется. Я пробовал strace -e open, но ничего толкового там нет.

**Comment by varlesh** [comment]
Да фиг знает. Может ему не нравится симлинк, что если удалить симлинк и продублировать значок emblem-link, переименовав в emblem-symbolic-link?

**Comment by horosgrisa** [comment]
Да нет. Симлинки должны работать.

**Comment by lonerTK** [comment]
не желаете под это иконочку ?:) 
http://pixs.ru/showimage/snimok11pn_3992564_18503096.png
да, знаю ав по линукс это "зашквар" но я такой параноик)+ он умеет сканит  файлы под winе ..
А если нет времени на это то нече страшного, не думаю что найдется еще люди такие паранорики как я )))))))))

**Comment by varlesh** [comment]
Ух )) 6 лет на линуксе, ни разу не ставил подобные программы
Ну уж раз просите, то сделаем. От вас имя иконки.

**Comment by lonerTK** [comment]
но тут /usr/share/applications/   нет  его иконки ,может он куда то в другом  месте прописывается хз )
давайте иконку для PlayOnLinux 
Name=PlayOnLinux
Icon=playonlinux

**Comment by varlesh** [comment]
@lonerTK я добавил plauonlinux и для антивируса, как dr-web. Посмотрите в~/.local/share/applications возможно есть значок запуска.

**Comment by lonerTK** [comment]
~/.local/share/applications тут нет.(если  вы имеете в виду иконку веба) 
а тут  /usr/local/share/applications  такое  
http://pixs.ru/showimage/snimok14pn_6276789_18507363.png

**Comment by varlesh** [comment]
ага, переименовал ed4cde3e94a4afb67630a85256b52a6331bd798d

**Comment by varlesh** [comment]
@lonerTK Скоро прилетят обновления для иконок и тем плазмы в Kubuntu.

**Comment by horosgrisa** [comment]
@varlesh Добавьте иконки 
- [ ] application-x-ms-dos-executable (exe-шники из WIndows)

**Comment by varlesh** [comment]
От вайна продублировал значок 2f57a2d2082eb7514f654dcd5ebbbb671439cd71

**Comment by horosgrisa** [comment]
@varlesh Может еще мне сделать цветовую схему для konsole/yakuake?

**Comment by varlesh** [comment]
м, я использую схему "Темная пастель" с фоном #222222.
![3](https://cloud.githubusercontent.com/assets/8083855/9426077/86b95b84-4932-11e5-8f99-ce7b23341e05.png)

**Comment by horosgrisa** [comment]
@varlesh А я могу сделать совместимую с solarized

**Comment by varlesh** [comment]
Да это мне кажется уже излишеством. Каждый сам под себя все равно подстраивает... У нас и так много всего о-0. Я еще думал про aurorae. Реп толстеет на глазах прям

**Comment by horosgrisa** [comment]
![after52](https://cloud.githubusercontent.com/assets/4980269/9426096/44a43128-4933-11e5-8307-f9c2153ee68c.png)
Вот примерно такое, но Papirus

**Comment by varlesh** [comment]
А под светлую оно не подойдет наверн. Цвета приятные

**Comment by horosgrisa** [comment]
Есть вариант и под светлую. Но я видел вот это https://dribbble.com/shots/1021755-Flat-UI-Terminal-Theme
Эта тема только для Mac ITerm, но можно сделать и для konsole

**Comment by varlesh** [comment]
А как можно вывести все использующиеся цвета, есть что-нибудь такое?

**Comment by horosgrisa** [comment]
Попробуйте эти 2 скрипта
http://cloud.udom.tk/index.php/s/DBJDjb8CzBgfH1E
http://cloud.udom.tk/index.php/s/eqrlB3quzFTUt8v

**Comment by varlesh** [comment]
Неплохо кстати, вот только красны надо ярче
![4](https://cloud.githubusercontent.com/assets/8083855/9426118/a76587ca-4934-11e5-93df-fe30bdbe61a5.png)

**Comment by horosgrisa** [comment]
Как вам предварительный вариант:
![after53](https://cloud.githubusercontent.com/assets/4980269/9426154/9f91a112-4936-11e5-8e5f-a754f00cfbc9.png)

**Comment by horosgrisa** [comment]
Даже вот такой:
![after54](https://cloud.githubusercontent.com/assets/4980269/9426156/f26853ea-4936-11e5-90c4-254fa7ccf175.png)
В предыдущем слишком яркий желтый цвет

**Comment by varlesh** [comment]
отлично, только вот этот малиновый очень яркий мне кажется.
Я чет похожее сделал
![5](https://cloud.githubusercontent.com/assets/8083855/9426157/0caa9600-4937-11e5-8ca7-4af0b4d4cb10.png)

**Comment by horosgrisa** [comment]
Темы совместимые с solarized выглядят вот так:
![after55](https://cloud.githubusercontent.com/assets/4980269/9426162/43971706-4937-11e5-9914-1c1484722e54.png)

**Comment by varlesh** [comment]
ну вот я на основе ее и делал, подправил желтый только и все Light цвета

**Comment by varlesh** [comment]
В вашем вотором скрине слишком сочные цвета, мне кажется надо сбавить насыщенность. Глаза будет резать в темноте

**Comment by horosgrisa** [comment]
Я тут проверил работу программ с этой цветовой схемой. Короче, нет смысла ее делать.

**Comment by horosgrisa** [comment]
Стоп, я понял. Еще не все потеряно

**Comment by varlesh** [comment]
Сам Paper, как и Papirus собственно, сделат в мягких цветах. Так что лучше избегать ярких насыщенных цветов. Они будут из стиля выбиваться

**Comment by horosgrisa** [comment]
Сделал. Темная тема выглядит очень даже недурно. А белая просто есть

**Comment by horosgrisa** [comment]
![after55](https://cloud.githubusercontent.com/assets/4980269/9426213/d236cc42-493a-11e5-9c98-67b117bb9bc1.png)

**Comment by varlesh** [comment]
Спасибо, проверять не буду пока )) Пойду спать уже...

**Comment by horosgrisa** [comment]
А можете поменять цвет у иконки архивов, уж очень он яркий

**Comment by varlesh** [comment]
ок 07faeb1e2725a9f6c60e765c3e089ec23a048795

**Comment by horosgrisa** [comment]
Отсувствуют иконки в меню Amarok, например

- [ ] Показать меню
- [ ] Управление обложками
- [ ] Схема списка воспроизведения
и т.д.

**Comment by varlesh** [comment]
@horosgrisa Эти иконки привязаны к конкретному пути и не подхватываются из темы значков.
Об этой проблеме я писал на форуме KDE:
https://forum.kde.org/viewtopic.php?f=17&t=127570
В теме доступна папка extra-icons  в ней есть дополнительные значки для amarok и krusader

**Comment by horosgrisa** [comment]
Ну и ну

**Comment by horosgrisa** [comment]
Но если я положу эти иконки в `/usr/share/kde4/apps/amarok` они будут использоватся?

**Comment by varlesh** [comment]
их можно в хомяк положить в ~/.kde/share/apps/amarok и они должны подцепится.
Они просто кадрированы и уменьшены/увеличены.... их по хорошему нужно перерисовывать

**Comment by varlesh** [comment]
Советую вам clementine, без танцев с бубном.

**Comment by horosgrisa** [comment]
Нет, я давным давно подсел на Amarok. А Clementine я тоже пользаовался, но он мне не понравился

**Comment by varlesh** [comment]
Ну не знай, мне клементин больше нравится. Амарок почему-то тормозит с большими коллекциями и вид у него страшноватый конечно.

**Comment by horosgrisa** [comment]
Но Amarok может использовать mysql базу данных, что частично решает проблему тормозов.

**Comment by varlesh** [comment]
@horosgrisa Гриш, вы используете kmail? Не подскажите, что там с иконкой в трее творится?
Я тестировал kubuntu 15.10 заметил и в kde-look отписались об этом.
Ранее в KDE4 использовалась иконка из плазмы вроде, а сейчас похоже с темы значков. Но какой-то рендеринг странный, все размывается (сам значок и цифра) при приходе нового письма.
П.С.: Пока сейчас на Unity сижу, жду когда починят баги в KDE. Потому нет возможности проверить...

**Comment by horosgrisa** [comment]
Иконка ужасная.

**Comment by varlesh** [comment]
Вот не понятно что с ней произошло... Это баг самого kmail или значков? С Breeze наблюдается такая проблема?

**Comment by horosgrisa** [comment]
Это иконка берется из темы значков, если использовать Breeze иконка все равно выглядит ужастно. Точнее, в Breeze ее нет вообще, она берется из Oxygen.

**Comment by varlesh** [comment]
Значит, что-то с рендерингом или не тот размер указали возможно. Спасибо за помощь ))
