### ISSUE TITLE
Тема плазмы 

### ISSUE THREAD

**Issue by horosgrisa** [varlesh/papirus-pack-kde#65]
Насколько я понимаю, тема для плазмы это просто Breeze с измененными цветами. Но недавно тема Breeze была обновлена, и стала куда лучше, а ваша тема испольует в качестве основы старую версию. Может стоить обновить её?

**Comment by varlesh** [comment]
Темы обновил. Оставил прозрачность в 10% во всех виджетах и панелях.

**Comment by FadeMind** [comment]
@varlesh progress bar for backlight is empty:
![screenshot_20151213_223957](https://cloud.githubusercontent.com/assets/9846948/11769551/72e6aa92-a1ea-11e5-8c52-ee8103a84cc1.png)

**Comment by varlesh** [comment]
Delete cache and apply theme:
rm ~/.cache/plasma*

**Comment by varlesh** [comment]
Themes updated as I could. If will problem, open a new issue.
