### ISSUE TITLE
[plasma theme] popup hint network manager have empty space instead of icon with full WIFI range

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#67]
**ISSUE**
![screenshot_20151214_180604](https://cloud.githubusercontent.com/assets/9846948/11787722/92a74ca8-a28d-11e5-92ad-a91d23618a8e.png)

![zaznaczenie_016](https://cloud.githubusercontent.com/assets/9846948/11787809/f803a4c0-a28d-11e5-8724-2bf085c93499.png)

Other icons looking fine:
![zaznaczenie_017](https://cloud.githubusercontent.com/assets/9846948/11787817/0273a8ce-a28e-11e5-958e-37d159a9c252.png)
![zaznaczenie_015](https://cloud.githubusercontent.com/assets/9846948/11787823/0bf112ce-a28e-11e5-830b-0026103c6317.png)

@varlesh  please looking at this. TY

**Comment by varlesh** [comment]
On Breeze icon showing?

**Comment by FadeMind** [comment]
yes.
![screenshot_20151214_182248](https://cloud.githubusercontent.com/assets/9846948/11788140/ca4d282e-a28f-11e5-87c9-ab1fb15f9a46.png)

**Comment by FadeMind** [comment]
@varlesh  on papirus dark it is the same - no icon in hint popup.

**Comment by varlesh** [comment]
please check

**Comment by FadeMind** [comment]
@varlesh Good work:
![screenshot_20151214_184105](https://cloud.githubusercontent.com/assets/9846948/11788620/451fd70c-a292-11e5-9dda-d6bf9ac0dc0a.png)
![screenshot_20151214_184211](https://cloud.githubusercontent.com/assets/9846948/11788649/67e8bb00-a292-11e5-9785-e2025d3d9f4d.png)
