### ISSUE TITLE
[plasma theme] If all windows are minimized, then IDK what Icons are active:

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#68]
**ISSUE**
Running and minimized are chrome, thunderbird and systemsettings
![screenshot_20151214_192612](https://cloud.githubusercontent.com/assets/9846948/11789833/e0aaa7b4-a298-11e5-9f4e-c092b0193377.png)
Running and minimized are chrome, thunderbird and opened systemsettings
![screenshot_20151214_192632](https://cloud.githubusercontent.com/assets/9846948/11789832/e0a6239c-a298-11e5-8e80-a068265c2ba9.png)
How should be - breeze plasma theme:
![screenshot_20151214_192702](https://cloud.githubusercontent.com/assets/9846948/11789834/e0ad4e10-a298-11e5-99fd-29fe119d3998.png)
@varlesh

**Comment by FadeMind** [comment]
NOTE: papius dark theme have the same behavior and appearance

**Comment by varlesh** [comment]
You mean indicate minimize task?
New Breeze not have minimized-top, minimize-down ... etc layers.

**Comment by varlesh** [comment]
Oh, sorry. On KF 5.17 this fixed. I update later, don't worry ))
![2015-12-14 21 57 48](https://cloud.githubusercontent.com/assets/8083855/11790642/e7b77d9c-a2ad-11e5-9b8f-e130ad7c4328.png)

**Comment by FadeMind** [comment]
See:
I have minimized all launched apps except systemsettings:
![screenshot_20151214_195932](https://cloud.githubusercontent.com/assets/9846948/11790718/8aadadfc-a29d-11e5-94d5-490458747a6a.png)
![screenshot_20151214_200103](https://cloud.githubusercontent.com/assets/9846948/11790720/8abc19aa-a29d-11e5-8ed9-11090835633e.png)
![screenshot_20151214_200030](https://cloud.githubusercontent.com/assets/9846948/11790719/8ab1043e-a29d-11e5-9ebe-52a577bfe2d2.png)
![screenshot_20151214_200127](https://cloud.githubusercontent.com/assets/9846948/11790721/8b1177c4-a29d-11e5-80c8-fa5a76215d51.png)

**Comment by varlesh** [comment]
This fixed on KF 5.17:
http://download.kde.org/stable/frameworks/5.17/
plasma-framework-5.17.0/src/desktoptheme/breeze/widgets/tasks.svgz

**Comment by varlesh** [comment]
@FadeMind please check

**Comment by FadeMind** [comment]
@varlesh  not fixed. nothing changes. I purged OFC plasma cache for apply changes.

**Comment by varlesh** [comment]
It's strange. I add black stroke for minimized tasks with 15% transparency

**Comment by FadeMind** [comment]
@varlesh 
Was fixed only for dark themes:
![screenshot_20151214_205300](https://cloud.githubusercontent.com/assets/9846948/11792100/ae3eb606-a2a4-11e5-864d-31679ba8320e.png)

![screenshot_20151214_205411](https://cloud.githubusercontent.com/assets/9846948/11792138/da4f11fa-a2a4-11e5-9c51-51a90b09b0d6.png)

standard papirus theme:
![screenshot_20151214_205503](https://cloud.githubusercontent.com/assets/9846948/11792165/f7d90d20-a2a4-11e5-8ef6-d3cec870ed07.png)

**Comment by varlesh** [comment]
Hm, on Papirus have:
minimized - 15% stroke only
normal - 30% stroke only
hover and focus 20% stroke and background
attention - red

**Comment by varlesh** [comment]
I create new document on Inkscape and save tasks again.

**Comment by FadeMind** [comment]
@varlesh 
FIXED. TY
![screenshot_20151214_210558](https://cloud.githubusercontent.com/assets/9846948/11792475/8f3591c4-a2a6-11e5-8cce-4c2c8740f2dc.png)

**Comment by varlesh** [comment]
It's bug Inkscape.
 For example see on Dolphin preview image:
papirus/widgets/glowbar.svgz
You see right position have blue gradient, but realy - all grey (open on Inkscape).
I don't know why this happened...

**Comment by FadeMind** [comment]
@varlesh Karbon have the same > all gey:
![screenshot_20151214_211631](https://cloud.githubusercontent.com/assets/9846948/11792754/f76859c4-a2a7-11e5-9667-740a54937ebf.png)

**Comment by varlesh** [comment]
But Dolphin?

**Comment by FadeMind** [comment]
Dolphin:
![screenshot_20151214_211949](https://cloud.githubusercontent.com/assets/9846948/11792830/7071b608-a2a8-11e5-8da6-b890da40195e.png)

**Comment by varlesh** [comment]
Yes - this inkscape bug

**Comment by FadeMind** [comment]
and Karbon...

**Comment by varlesh** [comment]
If create New document on inkscape and copy/paste all objects and save - bug not working.

**Comment by FadeMind** [comment]
Maybe commit new bug? :> https://inkscape.org/en/contribute/report-bugs/

**Comment by varlesh** [comment]
Yes, but latter. I create new symlinks for apps and busy
