### ISSUE TITLE
Тени или размытие шрифтов в панели в темной теме плазмы

### ISSUE THREAD

**Issue by horosgrisa** [varlesh/papirus-pack-kde#7]
Вот как это выглядит:
![after35](https://cloud.githubusercontent.com/assets/4980269/9292838/6ca8dba0-4416-11e5-808a-79492e0c1edc.png)

**Comment by varlesh** [comment]
Я знаю про этот баг, он закомментирован в colors. Это особенность отрисовки:
```
#disable glow efect font on TaskManager set ForegroundNormal=193,193,193
```
https://github.com/varlesh/papirus-pack-kde/blob/master/plasma-themes/papirus-dark/colors

**Comment by horosgrisa** [comment]
Ну а вот так никакие особенности отрисовки не проявляются:
![after36](https://cloud.githubusercontent.com/assets/4980269/9292880/e43484ec-4418-11e5-8e4b-69c67835c829.png)

**Comment by horosgrisa** [comment]
Это если подменить `colors` взяв его из `breeze-dark`

**Comment by varlesh** [comment]
Я же объяснил, что нужно заменить в секции [Colors:Window]:
на ForegroundNormal=193,193,193
При использовании ForegroundNormal=144,144,144 появляется эффект обводки. Потому как этот цвет считается темным...
Если оставить по-умолчанию ForegroundNormal=193,193,193, то придется перерисовывать все значки. Этот цвет светлее. Вот смотрите на своем скрине цвет значков и часов.
