### ISSUE TITLE
[PKGBUILD] LibreOffice images_papirus_dark.zip missing add VLC Skins

### ISSUE THREAD

**Issue by varlesh** [varlesh/papirus-pack-kde#71]
https://github.com/varlesh/papirus-pack-kde/blob/master/libreoffice-icons/images_papirus_dark.zip
```
package_libreoffice-style-papirus() {
    pkgdesc="Libreoffice Papirus theme "
    depends=('libreoffice')
    replaces=('libreoffice-papirus-theme')
    install -d ${pkgdir}/usr/lib/libreoffice/share/config
    cp -r ${srcdir}/${_repo}-${_git}/libreoffice-icons/images_papirus.zip ${pkgdir}/usr/lib/libreoffice/share/config
    install -D -m644  ${srcdir}/${_repo}-${_git}/libreoffice-icons/LICENSE ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
    find ${pkgdir}/usr -type f -exec chmod 644 {} \;
    find ${pkgdir}/usr -type d -exec chmod 755 {} \;
} 
```

**Comment by FadeMind** [comment]
@varlesh 
solution:

    `install -Dm644 -t "${pkgdir}/usr/lib/libreoffice/share/config/" ${srcdir}/${_pkgname}/libreoffice-icons/*.zip`
    `install -Dm644 -t "${pkgdir}/opt/libreoffice5.0/share/config/"  ${srcdir}/${_pkgname}/libreoffice-icons/*.zip`
    `find ${pkgdir}/usr -type f -exec chmod 644 {} \;`
    `find ${pkgdir}/usr -type d -exec chmod 755 {} \;`
    `find ${pkgdir}/opt -type f -exec chmod 644 {} \;`
    `find ${pkgdir}/opt -type d -exec chmod 755 {} \;`

**Comment by varlesh** [comment]
@horosgrisa Поправьте пожалуйста ))

**Comment by FadeMind** [comment]
@varlesh @horosgrisa I used `install -Dm644 -t` for files in PKGBUILD papirus-git: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=papirus-git
syntax
**install -Dm644 -t "DEST_DIR_PATH" "SRC_FILES_PATH_WITH_NAMES"**

    install -Dm644 -t "${pkgdir}/usr/share/color-schemes/"  ${srcdir}/${_pkgname}/color-schemes/*.colors
    install -Dm644 -t "${pkgdir}/usr/share/apps/konsole/"   ${srcdir}/${_pkgname}/konsole-colorschemes/*.colorscheme
    install -Dm644 -t "${pkgdir}/usr/share/konsole/"        ${srcdir}/${_pkgname}/konsole-colorschemes/*.colorscheme
    install -Dm644 -t "${pkgdir}/usr/lib/libreoffice/share/config/" ${srcdir}/${_pkgname}/libreoffice-icons/*.zip
    install -Dm644 -t "${pkgdir}/opt/libreoffice5.0/share/config/"  ${srcdir}/${_pkgname}/libreoffice-icons/*.zip

For directories used standard `cp -r`:

    cp -r ${srcdir}/${_pkgname}/look-and-feel/* ${pkgdir}/usr/share/plasma/look-and-feel/
    cp -r ${srcdir}/${_pkgname}/plasma-themes/papirus* ${pkgdir}/usr/share/plasma/desktoptheme/
    cp -r ${srcdir}/${_pkgname}/icons/papirus*                                  ${pkgdir}/usr/share/icons/
    cp -r ${srcdir}/${_pkgname}/icons/papirus/extra-icons/amarok/*              ${pkgdir}/usr/share/apps/amarok/icons/papirus/
    cp -r ${srcdir}/${_pkgname}/icons/papirus-black-panel/extra-icons/amarok/*  ${pkgdir}/usr/share/apps/amarok/icons/papirus-black-panel/
    cp -r ${srcdir}/${_pkgname}/icons/papirus-dark/extra-icons/amarok/*         ${pkgdir}/usr/share/apps/amarok/icons/papirus-dark/
    cp -r ${srcdir}/${_pkgname}/gtk-themes/papirus* ${pkgdir}/usr/share/themes/
    cp -r ${srcdir}/${_pkgname}/aurorae-themes/Papirus* ${pkgdir}/usr/share/aurorae/themes/
    cp -r ${srcdir}/${_pkgname}/yakuake-skins/papirus* ${pkgdir}/usr/share/apps/yakuake/skins/
    cp -r ${srcdir}/${_pkgname}/yakuake-skins/papirus* ${pkgdir}/usr/share/yakuake/skins/
    cp -r ${srcdir}/${_pkgname}/bomi-skin/Papirus ${pkgdir}/usr/share/bomi/skins/
    cp -r ${srcdir}/${_pkgname}/kmail-theme/papirus* ${pkgdir}/usr/share/messageviewer/themes/

**Comment by varlesh** [comment]
@FadeMind Please add Papirus Dark version for VLC:
https://github.com/varlesh/papirus-pack-kde/tree/master/vlc-skins/Papirus%20Dark
```
package_papirus-vlc-theme-git() {
    pkgdesc="Modified and adaptive Paper theme for VLC Media Player"
    options=('!strip')
    depends=('vlc')
    makedepends=('git')
    install -dm755 ${pkgdir}/usr/share/vlc/skins2
    cp -r ${srcdir}/${_pkgname}/vlc-skins/Papirus ${pkgdir}/usr/share/vlc/skins2/
    find ${pkgdir}/usr -type f -exec chmod 644 {} \;
    find ${pkgdir}/usr -type d -exec chmod 755 {} \;
}
```

**Comment by FadeMind** [comment]
@varlesh  https://aur.archlinux.org/cgit/aur.git/commit/?h=papirus-git&id=6deecfcaf5d0b72f5dba9239768a3fb27ebd7caa

**Comment by varlesh** [comment]
Thx :+1:
