### ISSUE TITLE
[GTK3] Some buttons using blue marking from breeze

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#73]
![screenshot_20151216_123251](https://cloud.githubusercontent.com/assets/9846948/11839830/25f85fce-a3f1-11e5-8243-ab57edd84b4c.png)
![screenshot_20151216_123221](https://cloud.githubusercontent.com/assets/9846948/11839833/2afa24d0-a3f1-11e5-9cf8-d9ad0167a42a.png)
@varlesh

**Comment by varlesh** [comment]
fixed ea4967590ab69a47891714bd397e85d400f5c5b7
