### ISSUE TITLE
window indicator? in icontasks is not visible when panel is vertical

### ISSUE THREAD

**Issue by marhkb** [varlesh/papirus-pack-kde#74]
The icons have no grey background in a vertical panel. Just compare the screenshots
![vertical_panel](https://cloud.githubusercontent.com/assets/3630213/11840147/ab896bea-a3f3-11e5-8821-e2e46b1e172c.png)
![horizontal_panel](https://cloud.githubusercontent.com/assets/3630213/11840149/b08b4dc0-a3f3-11e5-8709-08b854beac71.png)

**Comment by varlesh** [comment]
Not confirmed
![9](https://cloud.githubusercontent.com/assets/8083855/11844751/7379eeae-a421-11e5-8204-cdb2de4b5302.png)

**Comment by varlesh** [comment]
Maybe must del cache or theme folder and install again?

**Comment by marhkb** [comment]
Thank you varlesh. After removing .cache/plasma* everything now is as it should be. I did not know there was a cache.
btw: Papirus is getting better and better. Keep up the good work. :)

**Comment by varlesh** [comment]
Thx :)
