### ISSUE TITLE
[papirus vlc skin] issues

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#76]
Always On Top option not working.
Full Screen mode is corupted and looking:
![screenshot_20151218_112043](https://cloud.githubusercontent.com/assets/9846948/11894726/654cd9d2-a579-11e5-8964-752b8c3855c4.png)

**Comment by varlesh** [comment]
Cinema Mode - that Not Full Screen mode. Use F - key. Disable Sinema Mode - double click left mouse button on window.
Always On Top working, but after restart player - disabled

**Comment by FadeMind** [comment]
@varlesh thanks for explanation

**Comment by varlesh** [comment]
Cinema really not needed, but original theme (MinimalX) have this button. Also you can compare changes with MinimalX:
http://maverick07x.deviantart.com/art/VLC-MinimalX-385698882
- I delete all other colors and change button HightLight Color > Logs
- Little change colors and style
And found misprint:
![screen1](https://cloud.githubusercontent.com/assets/8083855/11896327/8e4a37ea-a596-11e5-838b-379deae54060.png)

**Comment by varlesh** [comment]
VLC have only this Actions:
https://github.com/videolan/vlc/blob/master/modules/gui/skins2/parser/interpreter.cpp
That very small
