### ISSUE TITLE
Incorporate light chromium theme

### ISSUE THREAD

**Issue by mingtang** [varlesh/papirus-pack-kde#81]
Hi there,

I found a light chromium theme (breeze flat) that works great with this pack:

https://forum.kde.org/viewtopic.php?f=285&t=123609

**Comment by varlesh** [comment]
Light theme not needed - use Papirus GTK.
![screenshot_20160116_100840](https://cloud.githubusercontent.com/assets/8083855/12371106/46f14474-bc39-11e5-9a0a-231bd670bdd7.png)
