### ISSUE TITLE
[k3b] Make papirus theme for k3b app.

### ISSUE THREAD

**Issue by FadeMind** [varlesh/papirus-pack-kde#85]
Sample theme structure:
[tomasz@arch ~]$ tree /usr/share/k3b/pics/73lab/
/usr/share/k3b/pics/73lab/
├── dialog_left.png
├── dialog_right.png
├── k3b.theme
├── media_audio.png
├── media_data.png
├── media_empty.png
├── media_left.png
├── media_mixed.png
├── media_none.png
├── media_video.png
├── probing.png
├── progress_fail.png
├── progress_right.png
├── progress_success.png
├── progress_working.png
├── project_left.png
├── project_right.png
├── splash.png
└── welcome_bg.png

GUIDE: http://www.k3b.org/themeshowto

@varlesh

**Comment by FadeMind** [comment]
73lab theme zip: 
[73lab.zip](https://github.com/varlesh/papirus-pack-kde/files/92874/73lab.zip)

**Comment by varlesh** [comment]
Oh sorry, i not have DVD-Rom (instead set SSD). And K3B not ported to KF5 now.
But i create template:
[papirus.tar.bz2.zip](https://github.com/varlesh/papirus-pack-kde/files/92898/papirus.tar.bz2.zip)

**Comment by FadeMind** [comment]
k3b is ported. Currently in AUR:

https://aur.archlinux.org/packages/k3b-frameworks-git/

Proof
![screenshot_20160116_145236](https://cloud.githubusercontent.com/assets/9846948/12372709/d8a65c98-bc60-11e5-8dd7-aba5b4e09468.png)

I'll add them in to papirus-git package. Please push them officialy in repo ;)

**Comment by varlesh** [comment]
Fine. Ok, i add themes later.
We have gigant pack now, omg :)

**Comment by varlesh** [comment]
added 130f11e2c300de3cc6c28c5f921622f59bf88d38
