### ISSUE TITLE
Dropbox icon is black instead of white when Papirus Dark Plasma theme is selected

### ISSUE THREAD

**Issue by pioneer** [varlesh/papirus-pack-kde#90]
I think it would be enough to make Dropbox icon just blue, as usual.
![screenshot6](https://cloud.githubusercontent.com/assets/200538/12913925/3d4390e0-cf2a-11e5-8b21-e59cc8461dc0.png). This issue may possibly overlap with #79, so please merge it into one if it makes sense.

**Comment by varlesh** [comment]
Please chek. I don't use KDE now

**Comment by varlesh** [comment]
And, sorry Plasma Theme not have dropbox icons - tray icons available on native KDE apps ( kmail, akregator, quassel and etc)
Use icon theme Papirus Dark or Papirus Black Panel and install manualy icons from dropbox (plese see man usr/share/icons/papirus-dark/extra-icons/tray/dropbox/README)

**Comment by varlesh** [comment]
@FadeMind please check new icons)) If 22px icons blured?

**Comment by pioneer** [comment]
On Ubuntu, Dropbox isn't in /opt/dropbox. I've just tried several locations and it works if I simply copy  new Dropbox icons from <git-repo>/icons/papirus-black-panel/extra-icons/tray/dropbox/hicolor/* to /usr/share/icons/papirus/. The only thing is that PNG icons in 16x16 folder are rendered as blurred in my KDE, so I've replaced them with SVG icons from 'scalable' folder.

**Comment by varlesh** [comment]
It's strange, because scalable icons already available on "status":
https://github.com/varlesh/papirus-pack-kde/tree/master/icons/papirus-dark/16x16/status

**Comment by varlesh** [comment]
Icons blured because SNI Proxy have bad rendering. You change panel size, and icons will be change size to. But SNI Proxy not rendering icons normaly.

**Comment by pioneer** [comment]
I use Papirus icons, Papirus color scheme, but Papirus Dark plasma theme. So thus Dropbox icons from Papirus icon theme were originally more black than white, before I replaced them a few minutes ago.

**Comment by varlesh** [comment]
Use Papirus Black Panel icons for Papirus Dark Plasma

**Comment by varlesh** [comment]
all dark style - Plasma Papirus Dark & Papirus Dark Icons
all light style - all dark style - Plasma Papirus & Papirus Icons
windows and colors lightm, but plasma dark  - Plasma Papirus Dark & Papirus Black Panel Icons

**Comment by FadeMind** [comment]
@varlesh dropbox using icons from `/opt/dropbox/images/` dirs in KDE Plasma. So, app don't care about current icon theme in system.
GTK based DE honor icon theme icons  for dropbox and replace them in tray.

**Comment by varlesh** [comment]
@FadeMind  new extra icons working for you?

**Comment by FadeMind** [comment]
xembedsniproxy don't render fine PNG files at all for dark plasma:
![screenshot_20160209_173919](https://cloud.githubusercontent.com/assets/9846948/12922984/21ac437a-cf54-11e5-9ca1-40d32817615a.png)
light plasma:
![screenshot_20160209_174115](https://cloud.githubusercontent.com/assets/9846948/12923028/540690be-cf54-11e5-9f9d-9226635ccd5d.png)

**Comment by varlesh** [comment]
Convert all icons to PNG - that bad solution. Maybe create request on xembedsniproxy?

**Comment by FadeMind** [comment]
Dropbox using own scheme for rendering icon tray. IF I force SVG here the icon is bad at all (taken from... dolphin)
xembedsniproxy is legacy for GTK non libappindicator apps like dropbox and you cannot do anything with this. 

Dropbox using qt5 in main app, but for tray it using PyGTK (sic!).

**Comment by varlesh** [comment]
Ok.
Why you dropbox icon use background?
![540690be-cf54-11e5-9f9d-9226635ccd5d](https://cloud.githubusercontent.com/assets/8083855/12923532/2275c656-cf67-11e5-9025-c87b14f153df.png)

**Comment by FadeMind** [comment]
xembedsniproxy don't render fine PNG file here.

**Comment by varlesh** [comment]
Ok i close, because this dropbox problem.
